DROP TABLE IF EXISTS t_glances_full_aggr_time_s_rnd1_max CASCADE;
CREATE TABLE t_glances_full_aggr_time_s_rnd1_max AS

SELECT

max("public".t_glances_full.rownr) as rownr,
row_number() over (partition by "public".t_glances_full.subid, "public".t_glances_full.time_s_rnd0 order by max("public".t_glances_full.rownr)) as rownr_aggr,
"public".t_glances_full.subid,
max("public".t_glances_full.time_s) as time_s,
"public".t_glances_full.time_s_rnd0,
max("public".t_glances_full.time_s_rnd1) as time_s_rnd1,
max("public".t_glances_full.dist_m_diff) as dist_m_diff,
max("public".t_glances_full.dist_m) as dist_m,
max("public".t_glances_full.dist_m_rnd0) as dist_m_rnd0,
max("public".t_glances_full.dist_m_rnd1) as dist_m_rnd1,
max("public".t_glances_full.round) as round,
"public".t_glances_full.round_txt,
max("public".t_glances_full.round_dist_m) as round_dist_m,
max("public".t_glances_full.round_dist_m_rnd0) as round_dist_m_rnd0,
max("public".t_glances_full.round_dist_m_rnd1) as round_dist_m_rnd1,
max("public".t_glances_full.gps_lat) as gps_lat,
max("public".t_glances_full.gps_long) as gps_long,
--
max("public".t_glances_full.s01_gps_lat) as s01_gps_lat,
max("public".t_glances_full.s01_gps_long) as s01_gps_long,
max("public".t_glances_full.s02_gps_lat) as s02_gps_lat,
max("public".t_glances_full.s02_gps_long) as s02_gps_long,
max("public".t_glances_full.s03_gps_lat) as s03_gps_lat,
max("public".t_glances_full.s03_gps_long) as s03_gps_long,
max("public".t_glances_full.s04_gps_lat) as s04_gps_lat,
max("public".t_glances_full.s04_gps_long) as s04_gps_long,
max("public".t_glances_full.s05_gps_lat) as s05_gps_lat,
max("public".t_glances_full.s05_gps_long) as s05_gps_long,
max("public".t_glances_full.s06_gps_lat) as s06_gps_lat,
max("public".t_glances_full.s06_gps_long) as s06_gps_long,
max("public".t_glances_full.s07_gps_lat) as s07_gps_lat,
max("public".t_glances_full.s07_gps_long) as s07_gps_long,
max("public".t_glances_full.s08_gps_lat) as s08_gps_lat,
max("public".t_glances_full.s08_gps_long) as s08_gps_long,
max("public".t_glances_full.s09_gps_lat) as s09_gps_lat,
max("public".t_glances_full.s09_gps_long) as s09_gps_long,
max("public".t_glances_full.s10_gps_lat) as s10_gps_lat,
max("public".t_glances_full.s10_gps_long) as s10_gps_long,
max("public".t_glances_full.s11_gps_lat) as s11_gps_lat,
max("public".t_glances_full.s11_gps_long) as s11_gps_long,
max("public".t_glances_full.s12_gps_lat) as s12_gps_lat,
max("public".t_glances_full.s12_gps_long) as s12_gps_long,
max("public".t_glances_full.s13_gps_lat) as s13_gps_lat,
max("public".t_glances_full.s13_gps_long) as s13_gps_long,
max("public".t_glances_full.s14_gps_lat) as s14_gps_lat,
max("public".t_glances_full.s14_gps_long) as s14_gps_long,
max("public".t_glances_full.s15_gps_lat) as s15_gps_lat,
max("public".t_glances_full.s15_gps_long) as s15_gps_long,
max("public".t_glances_full.s16_gps_lat) as s16_gps_lat,
max("public".t_glances_full.s16_gps_long) as s16_gps_long,
max("public".t_glances_full.s17_gps_lat) as s17_gps_lat,
max("public".t_glances_full.s17_gps_long) as s17_gps_long,
max("public".t_glances_full.s18_gps_lat) as s18_gps_lat,
max("public".t_glances_full.s18_gps_long) as s18_gps_long,
--
max("public".t_glances_full.s01_gps_dist_m) as s01_gps_dist_m,
max("public".t_glances_full.s02_gps_dist_m) as s02_gps_dist_m,
max("public".t_glances_full.s03_gps_dist_m) as s03_gps_dist_m,
max("public".t_glances_full.s04_gps_dist_m) as s04_gps_dist_m,
max("public".t_glances_full.s05_gps_dist_m) as s05_gps_dist_m,
max("public".t_glances_full.s06_gps_dist_m) as s06_gps_dist_m,
max("public".t_glances_full.s07_gps_dist_m) as s07_gps_dist_m,
max("public".t_glances_full.s08_gps_dist_m) as s08_gps_dist_m,
max("public".t_glances_full.s09_gps_dist_m) as s09_gps_dist_m,
max("public".t_glances_full.s10_gps_dist_m) as s10_gps_dist_m,
max("public".t_glances_full.s11_gps_dist_m) as s11_gps_dist_m,
max("public".t_glances_full.s12_gps_dist_m) as s12_gps_dist_m,
max("public".t_glances_full.s13_gps_dist_m) as s13_gps_dist_m,
max("public".t_glances_full.s14_gps_dist_m) as s14_gps_dist_m,
max("public".t_glances_full.s15_gps_dist_m) as s15_gps_dist_m,
max("public".t_glances_full.s16_gps_dist_m) as s16_gps_dist_m,
max("public".t_glances_full.s17_gps_dist_m) as s17_gps_dist_m,
max("public".t_glances_full.s18_gps_dist_m) as s18_gps_dist_m,
--
max("public".t_glances_full.s01_gps_dist_m_min) as s01_gps_dist_m_min,
max("public".t_glances_full.s02_gps_dist_m_min) as s02_gps_dist_m_min,
max("public".t_glances_full.s03_gps_dist_m_min) as s03_gps_dist_m_min,
max("public".t_glances_full.s04_gps_dist_m_min) as s04_gps_dist_m_min,
max("public".t_glances_full.s05_gps_dist_m_min) as s05_gps_dist_m_min,
max("public".t_glances_full.s06_gps_dist_m_min) as s06_gps_dist_m_min,
max("public".t_glances_full.s07_gps_dist_m_min) as s07_gps_dist_m_min,
max("public".t_glances_full.s08_gps_dist_m_min) as s08_gps_dist_m_min,
max("public".t_glances_full.s09_gps_dist_m_min) as s09_gps_dist_m_min,
max("public".t_glances_full.s10_gps_dist_m_min) as s10_gps_dist_m_min,
max("public".t_glances_full.s11_gps_dist_m_min) as s11_gps_dist_m_min,
max("public".t_glances_full.s12_gps_dist_m_min) as s12_gps_dist_m_min,
max("public".t_glances_full.s13_gps_dist_m_min) as s13_gps_dist_m_min,
max("public".t_glances_full.s14_gps_dist_m_min) as s14_gps_dist_m_min,
max("public".t_glances_full.s15_gps_dist_m_min) as s15_gps_dist_m_min,
max("public".t_glances_full.s16_gps_dist_m_min) as s16_gps_dist_m_min,
max("public".t_glances_full.s17_gps_dist_m_min) as s17_gps_dist_m_min,
max("public".t_glances_full.s18_gps_dist_m_min) as s18_gps_dist_m_min,
--
max("public".t_glances_full.s01_time_s_min) as s01_time_s_min,
max("public".t_glances_full.s02_time_s_min) as s02_time_s_min,
max("public".t_glances_full.s03_time_s_min) as s03_time_s_min,
max("public".t_glances_full.s04_time_s_min) as s04_time_s_min,
max("public".t_glances_full.s05_time_s_min) as s05_time_s_min,
max("public".t_glances_full.s06_time_s_min) as s06_time_s_min,
max("public".t_glances_full.s07_time_s_min) as s07_time_s_min,
max("public".t_glances_full.s08_time_s_min) as s08_time_s_min,
max("public".t_glances_full.s09_time_s_min) as s09_time_s_min,
max("public".t_glances_full.s10_time_s_min) as s10_time_s_min,
max("public".t_glances_full.s11_time_s_min) as s11_time_s_min,
max("public".t_glances_full.s12_time_s_min) as s12_time_s_min,
max("public".t_glances_full.s13_time_s_min) as s13_time_s_min,
max("public".t_glances_full.s14_time_s_min) as s14_time_s_min,
max("public".t_glances_full.s15_time_s_min) as s15_time_s_min,
max("public".t_glances_full.s16_time_s_min) as s16_time_s_min,
max("public".t_glances_full.s17_time_s_min) as s17_time_s_min,
max("public".t_glances_full.s18_time_s_min) as s18_time_s_min,
--
round(max("public".t_glances_full.s01_time_s_min), 0) as s01_time_s_min_rnd0,
round(max("public".t_glances_full.s02_time_s_min), 0) as s02_time_s_min_rnd0,
round(max("public".t_glances_full.s03_time_s_min), 0) as s03_time_s_min_rnd0,
round(max("public".t_glances_full.s04_time_s_min), 0) as s04_time_s_min_rnd0,
round(max("public".t_glances_full.s05_time_s_min), 0) as s05_time_s_min_rnd0,
round(max("public".t_glances_full.s06_time_s_min), 0) as s06_time_s_min_rnd0,
round(max("public".t_glances_full.s07_time_s_min), 0) as s07_time_s_min_rnd0,
round(max("public".t_glances_full.s08_time_s_min), 0) as s08_time_s_min_rnd0,
round(max("public".t_glances_full.s09_time_s_min), 0) as s09_time_s_min_rnd0,
round(max("public".t_glances_full.s10_time_s_min), 0) as s10_time_s_min_rnd0,
round(max("public".t_glances_full.s11_time_s_min), 0) as s11_time_s_min_rnd0,
round(max("public".t_glances_full.s12_time_s_min), 0) as s12_time_s_min_rnd0,
round(max("public".t_glances_full.s13_time_s_min), 0) as s13_time_s_min_rnd0,
round(max("public".t_glances_full.s14_time_s_min), 0) as s14_time_s_min_rnd0,
round(max("public".t_glances_full.s15_time_s_min), 0) as s15_time_s_min_rnd0,
round(max("public".t_glances_full.s16_time_s_min), 0) as s16_time_s_min_rnd0,
round(max("public".t_glances_full.s17_time_s_min), 0) as s17_time_s_min_rnd0,
round(max("public".t_glances_full.s18_time_s_min), 0) as s18_time_s_min_rnd0,
--
round(max("public".t_glances_full.s01_time_s_min), 1) as s01_time_s_min_rnd1,
round(max("public".t_glances_full.s02_time_s_min), 1) as s02_time_s_min_rnd1,
round(max("public".t_glances_full.s03_time_s_min), 1) as s03_time_s_min_rnd1,
round(max("public".t_glances_full.s04_time_s_min), 1) as s04_time_s_min_rnd1,
round(max("public".t_glances_full.s05_time_s_min), 1) as s05_time_s_min_rnd1,
round(max("public".t_glances_full.s06_time_s_min), 1) as s06_time_s_min_rnd1,
round(max("public".t_glances_full.s07_time_s_min), 1) as s07_time_s_min_rnd1,
round(max("public".t_glances_full.s08_time_s_min), 1) as s08_time_s_min_rnd1,
round(max("public".t_glances_full.s09_time_s_min), 1) as s09_time_s_min_rnd1,
round(max("public".t_glances_full.s10_time_s_min), 1) as s10_time_s_min_rnd1,
round(max("public".t_glances_full.s11_time_s_min), 1) as s11_time_s_min_rnd1,
round(max("public".t_glances_full.s12_time_s_min), 1) as s12_time_s_min_rnd1,
round(max("public".t_glances_full.s13_time_s_min), 1) as s13_time_s_min_rnd1,
round(max("public".t_glances_full.s14_time_s_min), 1) as s14_time_s_min_rnd1,
round(max("public".t_glances_full.s15_time_s_min), 1) as s15_time_s_min_rnd1,
round(max("public".t_glances_full.s16_time_s_min), 1) as s16_time_s_min_rnd1,
round(max("public".t_glances_full.s17_time_s_min), 1) as s17_time_s_min_rnd1,
round(max("public".t_glances_full.s18_time_s_min), 1) as s18_time_s_min_rnd1,
--
max("public".t_glances_full.s01_dist_m_min) as s01_dist_m_min,
max("public".t_glances_full.s02_dist_m_min) as s02_dist_m_min,
max("public".t_glances_full.s03_dist_m_min) as s03_dist_m_min,
max("public".t_glances_full.s04_dist_m_min) as s04_dist_m_min,
max("public".t_glances_full.s05_dist_m_min) as s05_dist_m_min,
max("public".t_glances_full.s06_dist_m_min) as s06_dist_m_min,
max("public".t_glances_full.s07_dist_m_min) as s07_dist_m_min,
max("public".t_glances_full.s08_dist_m_min) as s08_dist_m_min,
max("public".t_glances_full.s09_dist_m_min) as s09_dist_m_min,
max("public".t_glances_full.s10_dist_m_min) as s10_dist_m_min,
max("public".t_glances_full.s11_dist_m_min) as s11_dist_m_min,
max("public".t_glances_full.s12_dist_m_min) as s12_dist_m_min,
max("public".t_glances_full.s13_dist_m_min) as s13_dist_m_min,
max("public".t_glances_full.s14_dist_m_min) as s14_dist_m_min,
max("public".t_glances_full.s15_dist_m_min) as s15_dist_m_min,
max("public".t_glances_full.s16_dist_m_min) as s16_dist_m_min,
max("public".t_glances_full.s17_dist_m_min) as s17_dist_m_min,
max("public".t_glances_full.s18_dist_m_min) as s18_dist_m_min,
--
round(max("public".t_glances_full.s01_dist_m_min), 0) as s01_dist_m_min_rnd0,
round(max("public".t_glances_full.s02_dist_m_min), 0) as s02_dist_m_min_rnd0,
round(max("public".t_glances_full.s03_dist_m_min), 0) as s03_dist_m_min_rnd0,
round(max("public".t_glances_full.s04_dist_m_min), 0) as s04_dist_m_min_rnd0,
round(max("public".t_glances_full.s05_dist_m_min), 0) as s05_dist_m_min_rnd0,
round(max("public".t_glances_full.s06_dist_m_min), 0) as s06_dist_m_min_rnd0,
round(max("public".t_glances_full.s07_dist_m_min), 0) as s07_dist_m_min_rnd0,
round(max("public".t_glances_full.s08_dist_m_min), 0) as s08_dist_m_min_rnd0,
round(max("public".t_glances_full.s09_dist_m_min), 0) as s09_dist_m_min_rnd0,
round(max("public".t_glances_full.s10_dist_m_min), 0) as s10_dist_m_min_rnd0,
round(max("public".t_glances_full.s11_dist_m_min), 0) as s11_dist_m_min_rnd0,
round(max("public".t_glances_full.s12_dist_m_min), 0) as s12_dist_m_min_rnd0,
round(max("public".t_glances_full.s13_dist_m_min), 0) as s13_dist_m_min_rnd0,
round(max("public".t_glances_full.s14_dist_m_min), 0) as s14_dist_m_min_rnd0,
round(max("public".t_glances_full.s15_dist_m_min), 0) as s15_dist_m_min_rnd0,
round(max("public".t_glances_full.s16_dist_m_min), 0) as s16_dist_m_min_rnd0,
round(max("public".t_glances_full.s17_dist_m_min), 0) as s17_dist_m_min_rnd0,
round(max("public".t_glances_full.s18_dist_m_min), 0) as s18_dist_m_min_rnd0,
--
round(max("public".t_glances_full.s01_dist_m_min), 1) as s01_dist_m_min_rnd1,
round(max("public".t_glances_full.s02_dist_m_min), 1) as s02_dist_m_min_rnd1,
round(max("public".t_glances_full.s03_dist_m_min), 1) as s03_dist_m_min_rnd1,
round(max("public".t_glances_full.s04_dist_m_min), 1) as s04_dist_m_min_rnd1,
round(max("public".t_glances_full.s05_dist_m_min), 1) as s05_dist_m_min_rnd1,
round(max("public".t_glances_full.s06_dist_m_min), 1) as s06_dist_m_min_rnd1,
round(max("public".t_glances_full.s07_dist_m_min), 1) as s07_dist_m_min_rnd1,
round(max("public".t_glances_full.s08_dist_m_min), 1) as s08_dist_m_min_rnd1,
round(max("public".t_glances_full.s09_dist_m_min), 1) as s09_dist_m_min_rnd1,
round(max("public".t_glances_full.s10_dist_m_min), 1) as s10_dist_m_min_rnd1,
round(max("public".t_glances_full.s11_dist_m_min), 1) as s11_dist_m_min_rnd1,
round(max("public".t_glances_full.s12_dist_m_min), 1) as s12_dist_m_min_rnd1,
round(max("public".t_glances_full.s13_dist_m_min), 1) as s13_dist_m_min_rnd1,
round(max("public".t_glances_full.s14_dist_m_min), 1) as s14_dist_m_min_rnd1,
round(max("public".t_glances_full.s15_dist_m_min), 1) as s15_dist_m_min_rnd1,
round(max("public".t_glances_full.s16_dist_m_min), 1) as s16_dist_m_min_rnd1,
round(max("public".t_glances_full.s17_dist_m_min), 1) as s17_dist_m_min_rnd1,
round(max("public".t_glances_full.s18_dist_m_min), 1) as s18_dist_m_min_rnd1,
--
max("public".t_glances_full.s01_dist_s) as s01_dist_s,
max("public".t_glances_full.s02_dist_s) as s02_dist_s,
max("public".t_glances_full.s03_dist_s) as s03_dist_s,
max("public".t_glances_full.s04_dist_s) as s04_dist_s,
max("public".t_glances_full.s05_dist_s) as s05_dist_s,
max("public".t_glances_full.s06_dist_s) as s06_dist_s,
max("public".t_glances_full.s07_dist_s) as s07_dist_s,
max("public".t_glances_full.s08_dist_s) as s08_dist_s,
max("public".t_glances_full.s09_dist_s) as s09_dist_s,
max("public".t_glances_full.s10_dist_s) as s10_dist_s,
max("public".t_glances_full.s11_dist_s) as s11_dist_s,
max("public".t_glances_full.s12_dist_s) as s12_dist_s,
max("public".t_glances_full.s13_dist_s) as s13_dist_s,
max("public".t_glances_full.s14_dist_s) as s14_dist_s,
max("public".t_glances_full.s15_dist_s) as s15_dist_s,
max("public".t_glances_full.s16_dist_s) as s16_dist_s,
max("public".t_glances_full.s17_dist_s) as s17_dist_s,
max("public".t_glances_full.s18_dist_s) as s18_dist_s,
--
max("public".t_glances_full.s01_dist_s_rnd0) as s01_dist_s_rnd0,
max("public".t_glances_full.s02_dist_s_rnd0) as s02_dist_s_rnd0,
max("public".t_glances_full.s03_dist_s_rnd0) as s03_dist_s_rnd0,
max("public".t_glances_full.s04_dist_s_rnd0) as s04_dist_s_rnd0,
max("public".t_glances_full.s05_dist_s_rnd0) as s05_dist_s_rnd0,
max("public".t_glances_full.s06_dist_s_rnd0) as s06_dist_s_rnd0,
max("public".t_glances_full.s07_dist_s_rnd0) as s07_dist_s_rnd0,
max("public".t_glances_full.s08_dist_s_rnd0) as s08_dist_s_rnd0,
max("public".t_glances_full.s09_dist_s_rnd0) as s09_dist_s_rnd0,
max("public".t_glances_full.s10_dist_s_rnd0) as s10_dist_s_rnd0,
max("public".t_glances_full.s11_dist_s_rnd0) as s11_dist_s_rnd0,
max("public".t_glances_full.s12_dist_s_rnd0) as s12_dist_s_rnd0,
max("public".t_glances_full.s13_dist_s_rnd0) as s13_dist_s_rnd0,
max("public".t_glances_full.s14_dist_s_rnd0) as s14_dist_s_rnd0,
max("public".t_glances_full.s15_dist_s_rnd0) as s15_dist_s_rnd0,
max("public".t_glances_full.s16_dist_s_rnd0) as s16_dist_s_rnd0,
max("public".t_glances_full.s17_dist_s_rnd0) as s17_dist_s_rnd0,
max("public".t_glances_full.s18_dist_s_rnd0) as s18_dist_s_rnd0,
--
max("public".t_glances_full.s01_dist_s_rnd1) as s01_dist_s_rnd1,
max("public".t_glances_full.s02_dist_s_rnd1) as s02_dist_s_rnd1,
max("public".t_glances_full.s03_dist_s_rnd1) as s03_dist_s_rnd1,
max("public".t_glances_full.s04_dist_s_rnd1) as s04_dist_s_rnd1,
max("public".t_glances_full.s05_dist_s_rnd1) as s05_dist_s_rnd1,
max("public".t_glances_full.s06_dist_s_rnd1) as s06_dist_s_rnd1,
max("public".t_glances_full.s07_dist_s_rnd1) as s07_dist_s_rnd1,
max("public".t_glances_full.s08_dist_s_rnd1) as s08_dist_s_rnd1,
max("public".t_glances_full.s09_dist_s_rnd1) as s09_dist_s_rnd1,
max("public".t_glances_full.s10_dist_s_rnd1) as s10_dist_s_rnd1,
max("public".t_glances_full.s11_dist_s_rnd1) as s11_dist_s_rnd1,
max("public".t_glances_full.s12_dist_s_rnd1) as s12_dist_s_rnd1,
max("public".t_glances_full.s13_dist_s_rnd1) as s13_dist_s_rnd1,
max("public".t_glances_full.s14_dist_s_rnd1) as s14_dist_s_rnd1,
max("public".t_glances_full.s15_dist_s_rnd1) as s15_dist_s_rnd1,
max("public".t_glances_full.s16_dist_s_rnd1) as s16_dist_s_rnd1,
max("public".t_glances_full.s17_dist_s_rnd1) as s17_dist_s_rnd1,
max("public".t_glances_full.s18_dist_s_rnd1) as s18_dist_s_rnd1,
--
max("public".t_glances_full.s01_dist_m) as s01_dist_m,
max("public".t_glances_full.s02_dist_m) as s02_dist_m,
max("public".t_glances_full.s03_dist_m) as s03_dist_m,
max("public".t_glances_full.s04_dist_m) as s04_dist_m,
max("public".t_glances_full.s05_dist_m) as s05_dist_m,
max("public".t_glances_full.s06_dist_m) as s06_dist_m,
max("public".t_glances_full.s07_dist_m) as s07_dist_m,
max("public".t_glances_full.s08_dist_m) as s08_dist_m,
max("public".t_glances_full.s09_dist_m) as s09_dist_m,
max("public".t_glances_full.s10_dist_m) as s10_dist_m,
max("public".t_glances_full.s11_dist_m) as s11_dist_m,
max("public".t_glances_full.s12_dist_m) as s12_dist_m,
max("public".t_glances_full.s13_dist_m) as s13_dist_m,
max("public".t_glances_full.s14_dist_m) as s14_dist_m,
max("public".t_glances_full.s15_dist_m) as s15_dist_m,
max("public".t_glances_full.s16_dist_m) as s16_dist_m,
max("public".t_glances_full.s17_dist_m) as s17_dist_m,
max("public".t_glances_full.s18_dist_m) as s18_dist_m,
--
max("public".t_glances_full.s01_dist_m_rnd0) as s01_dist_m_rnd0,
max("public".t_glances_full.s02_dist_m_rnd0) as s02_dist_m_rnd0,
max("public".t_glances_full.s03_dist_m_rnd0) as s03_dist_m_rnd0,
max("public".t_glances_full.s04_dist_m_rnd0) as s04_dist_m_rnd0,
max("public".t_glances_full.s05_dist_m_rnd0) as s05_dist_m_rnd0,
max("public".t_glances_full.s06_dist_m_rnd0) as s06_dist_m_rnd0,
max("public".t_glances_full.s07_dist_m_rnd0) as s07_dist_m_rnd0,
max("public".t_glances_full.s08_dist_m_rnd0) as s08_dist_m_rnd0,
max("public".t_glances_full.s09_dist_m_rnd0) as s09_dist_m_rnd0,
max("public".t_glances_full.s10_dist_m_rnd0) as s10_dist_m_rnd0,
max("public".t_glances_full.s11_dist_m_rnd0) as s11_dist_m_rnd0,
max("public".t_glances_full.s12_dist_m_rnd0) as s12_dist_m_rnd0,
max("public".t_glances_full.s13_dist_m_rnd0) as s13_dist_m_rnd0,
max("public".t_glances_full.s14_dist_m_rnd0) as s14_dist_m_rnd0,
max("public".t_glances_full.s15_dist_m_rnd0) as s15_dist_m_rnd0,
max("public".t_glances_full.s16_dist_m_rnd0) as s16_dist_m_rnd0,
max("public".t_glances_full.s17_dist_m_rnd0) as s17_dist_m_rnd0,
max("public".t_glances_full.s18_dist_m_rnd0) as s18_dist_m_rnd0,
--
max("public".t_glances_full.s01_dist_m_rnd1) as s01_dist_m_rnd1,
max("public".t_glances_full.s02_dist_m_rnd1) as s02_dist_m_rnd1,
max("public".t_glances_full.s03_dist_m_rnd1) as s03_dist_m_rnd1,
max("public".t_glances_full.s04_dist_m_rnd1) as s04_dist_m_rnd1,
max("public".t_glances_full.s05_dist_m_rnd1) as s05_dist_m_rnd1,
max("public".t_glances_full.s06_dist_m_rnd1) as s06_dist_m_rnd1,
max("public".t_glances_full.s07_dist_m_rnd1) as s07_dist_m_rnd1,
max("public".t_glances_full.s08_dist_m_rnd1) as s08_dist_m_rnd1,
max("public".t_glances_full.s09_dist_m_rnd1) as s09_dist_m_rnd1,
max("public".t_glances_full.s10_dist_m_rnd1) as s10_dist_m_rnd1,
max("public".t_glances_full.s11_dist_m_rnd1) as s11_dist_m_rnd1,
max("public".t_glances_full.s12_dist_m_rnd1) as s12_dist_m_rnd1,
max("public".t_glances_full.s13_dist_m_rnd1) as s13_dist_m_rnd1,
max("public".t_glances_full.s14_dist_m_rnd1) as s14_dist_m_rnd1,
max("public".t_glances_full.s15_dist_m_rnd1) as s15_dist_m_rnd1,
max("public".t_glances_full.s16_dist_m_rnd1) as s16_dist_m_rnd1,
max("public".t_glances_full.s17_dist_m_rnd1) as s17_dist_m_rnd1,
max("public".t_glances_full.s18_dist_m_rnd1) as s18_dist_m_rnd1,
--
-- max("public".t_glances_full.s01_ttc_s) as s01_ttc_s,
-- max("public".t_glances_full.s02_ttc_s) as s02_ttc_s,
-- max("public".t_glances_full.s03_ttc_s) as s03_ttc_s,
-- max("public".t_glances_full.s04_ttc_s) as s04_ttc_s,
-- max("public".t_glances_full.s05_ttc_s) as s05_ttc_s,
-- max("public".t_glances_full.s06_ttc_s) as s06_ttc_s,
-- max("public".t_glances_full.s07_ttc_s) as s07_ttc_s,
-- max("public".t_glances_full.s08_ttc_s) as s08_ttc_s,
-- max("public".t_glances_full.s09_ttc_s) as s09_ttc_s,
-- max("public".t_glances_full.s10_ttc_s) as s10_ttc_s,
-- max("public".t_glances_full.s11_ttc_s) as s11_ttc_s,
-- max("public".t_glances_full.s12_ttc_s) as s12_ttc_s,
-- max("public".t_glances_full.s13_ttc_s) as s13_ttc_s,
-- max("public".t_glances_full.s14_ttc_s) as s14_ttc_s,
-- max("public".t_glances_full.s15_ttc_s) as s15_ttc_s,
-- max("public".t_glances_full.s16_ttc_s) as s16_ttc_s,
-- max("public".t_glances_full.s17_ttc_s) as s17_ttc_s,
-- max("public".t_glances_full.s18_ttc_s) as s18_ttc_s,
-- --
-- max("public".t_glances_full.s01_ttc_s_rnd) as s01_ttc_s_rnd,
-- max("public".t_glances_full.s02_ttc_s_rnd) as s02_ttc_s_rnd,
-- max("public".t_glances_full.s03_ttc_s_rnd) as s03_ttc_s_rnd,
-- max("public".t_glances_full.s04_ttc_s_rnd) as s04_ttc_s_rnd,
-- max("public".t_glances_full.s05_ttc_s_rnd) as s05_ttc_s_rnd,
-- max("public".t_glances_full.s06_ttc_s_rnd) as s06_ttc_s_rnd,
-- max("public".t_glances_full.s07_ttc_s_rnd) as s07_ttc_s_rnd,
-- max("public".t_glances_full.s08_ttc_s_rnd) as s08_ttc_s_rnd,
-- max("public".t_glances_full.s09_ttc_s_rnd) as s09_ttc_s_rnd,
-- max("public".t_glances_full.s10_ttc_s_rnd) as s10_ttc_s_rnd,
-- max("public".t_glances_full.s11_ttc_s_rnd) as s11_ttc_s_rnd,
-- max("public".t_glances_full.s12_ttc_s_rnd) as s12_ttc_s_rnd,
-- max("public".t_glances_full.s13_ttc_s_rnd) as s13_ttc_s_rnd,
-- max("public".t_glances_full.s14_ttc_s_rnd) as s14_ttc_s_rnd,
-- max("public".t_glances_full.s15_ttc_s_rnd) as s15_ttc_s_rnd,
-- max("public".t_glances_full.s16_ttc_s_rnd) as s16_ttc_s_rnd,
-- max("public".t_glances_full.s17_ttc_s_rnd) as s17_ttc_s_rnd,
-- max("public".t_glances_full.s18_ttc_s_rnd) as s18_ttc_s_rnd,
--
-- max("public".t_glances_full.speed_kmh) as speed_kmh,
-- max("public".t_glances_full.speed_kmh_diff) as speed_kmh_diff,
-- max("public".t_glances_full.acclat_ms2) as acclat_ms2,
-- max("public".t_glances_full.acclat_ms2_diff) as acclat_ms2_diff,
-- max("public".t_glances_full.acclong_ms2) as acclong_ms2,
-- max("public".t_glances_full.acclong_ms2_diff) as acclong_ms2_diff,
-- max("public".t_glances_full.yawrate_degs) as yawrate_degs,
-- max("public".t_glances_full.yawrate_degs_diff) as yawrate_degs_diff,
-- max("public".t_glances_full.brakepress_bar) as brakepress_bar,
-- max("public".t_glances_full.brakepress_bar_diff) as brakepress_bar_diff,
-- max("public".t_glances_full.brakepress_status) as brakepress_status,
-- max("public".t_glances_full.steerangle_deg) as steerangle_deg,
-- max("public".t_glances_full.steerangle_deg_diff) as steerangle_deg_diff,
-- max("public".t_glances_full.steerangle_speed) as steerangle_speed,
-- max("public".t_glances_full.steerangle_speed_diff) as steerangle_speed_diff,
-- max("public".t_glances_full.accpedalpos_perc) as accpedalpos_perc,
-- max("public".t_glances_full.accpedalpos_perc_diff) as accpedalpos_perc_diff,
-- max("public".t_glances_full.ind_left) as ind_left,
-- max("public".t_glances_full.ind_right) as ind_right,
-- max("public".t_glances_full.ind) as ind,
-- max("public".t_glances_full.ldw_side) as ldw_side,
-- max("public".t_glances_full.ldw_tlc_s) as ldw_tlc_s,
-- max("public".t_glances_full.ldw_tlc_s_diff) as ldw_tlc_s_diff,
-- max("public".t_glances_full.ldw_dlc_m) as ldw_dlc_m,
-- max("public".t_glances_full.ldw_dlc_m_diff) as ldw_dlc_m_diff,
-- max("public".t_glances_full.dist_intersect_m) as dist_intersect_m,
-- max("public".t_glances_full.road_type) as road_type,
-- max("public".t_glances_full.lanes_count) as lanes_count,
--
max("public".t_glances_full.ind) as ind,
max("public".t_glances_full.ind_left) as ind_left,
max("public".t_glances_full.ind_right) as ind_right,
--
max("public".t_glances_full.glance_dir) as glance_dir,
max("public".t_glances_full.glance_dir_v2) as glance_dir_v2,
max("public".t_glances_full.glance_dir_txt) as glance_dir_txt,
max("public".t_glances_full.glance_dir_v2_txt) as glance_dir_v2_txt,
max("public".t_glances_full.glance_time_s_start) as glance_time_s_start,
max("public".t_glances_full.glance_time_s_end) as glance_time_s_end,
max("public".t_glances_full.glance_dur_s) as glance_dur_s,
max("public".t_glances_full.glance_dur_s_dir_cum) as glance_dur_s_dir_cum,
max("public".t_glances_full.glance_nr) as glance_nr,
max("public".t_glances_full.glance_nr_dir) as glance_nr_dir,

--
max("public".t_glances_full.filename) as filename,
max("public".t_glances_full.cond) as cond,
max("public".t_glances_full.exid) as exid,
max("public".t_glances_full."date") as "date"

FROM
"public".t_glances_full

GROUP BY
"public".t_glances_full.subid,
"public".t_glances_full.round_txt,
"public".t_glances_full.time_s_rnd0

ORDER BY
max("public".t_glances_full.rownr)