DROP TABLE IF EXISTS t_glance_full_aggr_time_s_rnd0 CASCADE;
CREATE TABLE t_glance_full_aggr_time_s_rnd0 AS

SELECT
max("public".t_glance_full.rownr) as rownr,
row_number() over (partition by "public".t_glance_full.subid, "public".t_glance_full.time_s_rnd0 order by max("public".t_glance_full.rownr)) as rownr_aggr,
"public".t_glance_full.subid,
max("public".t_glance_full.time_s) as time_s,
"public".t_glance_full.time_s_rnd0,
max("public".t_glance_full.time_s_rnd1) as time_s_rnd1,
max("public".t_glance_full.dist_m) as dist_m,
max("public".t_glance_full.dist_m_rnd0) as dist_m_rnd0,
max("public".t_glance_full.dist_m_rnd1) as dist_m_rnd1,
max("public".t_glance_full.round) as round,
"public".t_glance_full.round_txt,
--
max("public".t_glance_full.ind) as ind,
max("public".t_glance_full.ind_left) as ind_left,
max("public".t_glance_full.ind_right) as ind_right,
--
max("public".t_glance_full.glance_dir) as glance_dir,
max("public".t_glance_full.glance_dir_txt) as glance_dir_txt,
max("public".t_glance_full.glance_dir_v2) as glance_dir_v2,
max("public".t_glance_full.glance_dir_v2_txt) as glance_dir_v2_txt,
max("public".t_glance_full.glance_time_s_start) as glance_time_s_start,
max("public".t_glance_full.glance_time_s_end) as glance_time_s_end,
max("public".t_glance_full.glance_dur_s) as glance_dur_s,
max("public".t_glance_full.glance_dur_s_dir_cum) as glance_dur_s_dir_cum,
max("public".t_glance_full.glance_nr) as glance_nr,
max("public".t_glance_full.glance_nr_dir) as glance_nr_dir,
--
max("public".t_glance_full.s01_dist_s) as s01_dist_s,
max("public".t_glance_full.s02_dist_s) as s02_dist_s,
max("public".t_glance_full.s03_dist_s) as s03_dist_s,
max("public".t_glance_full.s04_dist_s) as s04_dist_s,
max("public".t_glance_full.s05_dist_s) as s05_dist_s,
max("public".t_glance_full.s06_dist_s) as s06_dist_s,
max("public".t_glance_full.s07_dist_s) as s07_dist_s,
max("public".t_glance_full.s08_dist_s) as s08_dist_s,
max("public".t_glance_full.s09_dist_s) as s09_dist_s,
max("public".t_glance_full.s10_dist_s) as s10_dist_s,
max("public".t_glance_full.s11_dist_s) as s11_dist_s,
max("public".t_glance_full.s12_dist_s) as s12_dist_s,
max("public".t_glance_full.s13_dist_s) as s13_dist_s,
max("public".t_glance_full.s14_dist_s) as s14_dist_s,
max("public".t_glance_full.s15_dist_s) as s15_dist_s,
max("public".t_glance_full.s16_dist_s) as s16_dist_s,
max("public".t_glance_full.s17_dist_s) as s17_dist_s,
max("public".t_glance_full.s18_dist_s) as s18_dist_s,
--
max("public".t_glance_full.s01_dist_s_rnd0) as s01_dist_s_rnd0,
max("public".t_glance_full.s02_dist_s_rnd0) as s02_dist_s_rnd0,
max("public".t_glance_full.s03_dist_s_rnd0) as s03_dist_s_rnd0,
max("public".t_glance_full.s04_dist_s_rnd0) as s04_dist_s_rnd0,
max("public".t_glance_full.s05_dist_s_rnd0) as s05_dist_s_rnd0,
max("public".t_glance_full.s06_dist_s_rnd0) as s06_dist_s_rnd0,
max("public".t_glance_full.s07_dist_s_rnd0) as s07_dist_s_rnd0,
max("public".t_glance_full.s08_dist_s_rnd0) as s08_dist_s_rnd0,
max("public".t_glance_full.s09_dist_s_rnd0) as s09_dist_s_rnd0,
max("public".t_glance_full.s10_dist_s_rnd0) as s10_dist_s_rnd0,
max("public".t_glance_full.s11_dist_s_rnd0) as s11_dist_s_rnd0,
max("public".t_glance_full.s12_dist_s_rnd0) as s12_dist_s_rnd0,
max("public".t_glance_full.s13_dist_s_rnd0) as s13_dist_s_rnd0,
max("public".t_glance_full.s14_dist_s_rnd0) as s14_dist_s_rnd0,
max("public".t_glance_full.s15_dist_s_rnd0) as s15_dist_s_rnd0,
max("public".t_glance_full.s16_dist_s_rnd0) as s16_dist_s_rnd0,
max("public".t_glance_full.s17_dist_s_rnd0) as s17_dist_s_rnd0,
max("public".t_glance_full.s18_dist_s_rnd0) as s18_dist_s_rnd0,
--
max("public".t_glance_full.s01_dist_s_rnd1) as s01_dist_s_rnd1,
max("public".t_glance_full.s02_dist_s_rnd1) as s02_dist_s_rnd1,
max("public".t_glance_full.s03_dist_s_rnd1) as s03_dist_s_rnd1,
max("public".t_glance_full.s04_dist_s_rnd1) as s04_dist_s_rnd1,
max("public".t_glance_full.s05_dist_s_rnd1) as s05_dist_s_rnd1,
max("public".t_glance_full.s06_dist_s_rnd1) as s06_dist_s_rnd1,
max("public".t_glance_full.s07_dist_s_rnd1) as s07_dist_s_rnd1,
max("public".t_glance_full.s08_dist_s_rnd1) as s08_dist_s_rnd1,
max("public".t_glance_full.s09_dist_s_rnd1) as s09_dist_s_rnd1,
max("public".t_glance_full.s10_dist_s_rnd1) as s10_dist_s_rnd1,
max("public".t_glance_full.s11_dist_s_rnd1) as s11_dist_s_rnd1,
max("public".t_glance_full.s12_dist_s_rnd1) as s12_dist_s_rnd1,
max("public".t_glance_full.s13_dist_s_rnd1) as s13_dist_s_rnd1,
max("public".t_glance_full.s14_dist_s_rnd1) as s14_dist_s_rnd1,
max("public".t_glance_full.s15_dist_s_rnd1) as s15_dist_s_rnd1,
max("public".t_glance_full.s16_dist_s_rnd1) as s16_dist_s_rnd1,
max("public".t_glance_full.s17_dist_s_rnd1) as s17_dist_s_rnd1,
max("public".t_glance_full.s18_dist_s_rnd1) as s18_dist_s_rnd1,
--
max("public".t_glance_full.s01_dist_m) as s01_dist_m,
max("public".t_glance_full.s02_dist_m) as s02_dist_m,
max("public".t_glance_full.s03_dist_m) as s03_dist_m,
max("public".t_glance_full.s04_dist_m) as s04_dist_m,
max("public".t_glance_full.s05_dist_m) as s05_dist_m,
max("public".t_glance_full.s06_dist_m) as s06_dist_m,
max("public".t_glance_full.s07_dist_m) as s07_dist_m,
max("public".t_glance_full.s08_dist_m) as s08_dist_m,
max("public".t_glance_full.s09_dist_m) as s09_dist_m,
max("public".t_glance_full.s10_dist_m) as s10_dist_m,
max("public".t_glance_full.s11_dist_m) as s11_dist_m,
max("public".t_glance_full.s12_dist_m) as s12_dist_m,
max("public".t_glance_full.s13_dist_m) as s13_dist_m,
max("public".t_glance_full.s14_dist_m) as s14_dist_m,
max("public".t_glance_full.s15_dist_m) as s15_dist_m,
max("public".t_glance_full.s16_dist_m) as s16_dist_m,
max("public".t_glance_full.s17_dist_m) as s17_dist_m,
max("public".t_glance_full.s18_dist_m) as s18_dist_m,
--
max("public".t_glance_full.s01_dist_m_rnd0) as s01_dist_m_rnd0,
max("public".t_glance_full.s02_dist_m_rnd0) as s02_dist_m_rnd0,
max("public".t_glance_full.s03_dist_m_rnd0) as s03_dist_m_rnd0,
max("public".t_glance_full.s04_dist_m_rnd0) as s04_dist_m_rnd0,
max("public".t_glance_full.s05_dist_m_rnd0) as s05_dist_m_rnd0,
max("public".t_glance_full.s06_dist_m_rnd0) as s06_dist_m_rnd0,
max("public".t_glance_full.s07_dist_m_rnd0) as s07_dist_m_rnd0,
max("public".t_glance_full.s08_dist_m_rnd0) as s08_dist_m_rnd0,
max("public".t_glance_full.s09_dist_m_rnd0) as s09_dist_m_rnd0,
max("public".t_glance_full.s10_dist_m_rnd0) as s10_dist_m_rnd0,
max("public".t_glance_full.s11_dist_m_rnd0) as s11_dist_m_rnd0,
max("public".t_glance_full.s12_dist_m_rnd0) as s12_dist_m_rnd0,
max("public".t_glance_full.s13_dist_m_rnd0) as s13_dist_m_rnd0,
max("public".t_glance_full.s14_dist_m_rnd0) as s14_dist_m_rnd0,
max("public".t_glance_full.s15_dist_m_rnd0) as s15_dist_m_rnd0,
max("public".t_glance_full.s16_dist_m_rnd0) as s16_dist_m_rnd0,
max("public".t_glance_full.s17_dist_m_rnd0) as s17_dist_m_rnd0,
max("public".t_glance_full.s18_dist_m_rnd0) as s18_dist_m_rnd0,
--
max("public".t_glance_full.s01_dist_m_rnd1) as s01_dist_m_rnd1,
max("public".t_glance_full.s02_dist_m_rnd1) as s02_dist_m_rnd1,
max("public".t_glance_full.s03_dist_m_rnd1) as s03_dist_m_rnd1,
max("public".t_glance_full.s04_dist_m_rnd1) as s04_dist_m_rnd1,
max("public".t_glance_full.s05_dist_m_rnd1) as s05_dist_m_rnd1,
max("public".t_glance_full.s06_dist_m_rnd1) as s06_dist_m_rnd1,
max("public".t_glance_full.s07_dist_m_rnd1) as s07_dist_m_rnd1,
max("public".t_glance_full.s08_dist_m_rnd1) as s08_dist_m_rnd1,
max("public".t_glance_full.s09_dist_m_rnd1) as s09_dist_m_rnd1,
max("public".t_glance_full.s10_dist_m_rnd1) as s10_dist_m_rnd1,
max("public".t_glance_full.s11_dist_m_rnd1) as s11_dist_m_rnd1,
max("public".t_glance_full.s12_dist_m_rnd1) as s12_dist_m_rnd1,
max("public".t_glance_full.s13_dist_m_rnd1) as s13_dist_m_rnd1,
max("public".t_glance_full.s14_dist_m_rnd1) as s14_dist_m_rnd1,
max("public".t_glance_full.s15_dist_m_rnd1) as s15_dist_m_rnd1,
max("public".t_glance_full.s16_dist_m_rnd1) as s16_dist_m_rnd1,
max("public".t_glance_full.s17_dist_m_rnd1) as s17_dist_m_rnd1,
max("public".t_glance_full.s18_dist_m_rnd1) as s18_dist_m_rnd1

FROM
"public".t_glance_full

GROUP BY
"public".t_glance_full.subid,
"public".t_glance_full.round_txt,
"public".t_glance_full.time_s_rnd0

ORDER BY
max("public".t_glance_full.rownr)