CREATE OR REPLACE VIEW v_can_gesamt_v3_situation_distanz_v2_min AS

SELECT
"public".v_can_gesamt_v3_situation_distanz.znr,
"public".v_can_gesamt_v3_situation_distanz.znr_vp,
"public".v_can_gesamt_v3_situation_distanz.vp,
"public".v_can_gesamt_v3_situation_distanz.datei,
"public".v_can_gesamt_v3_situation_distanz.zeit_s,
"public".v_can_gesamt_v3_situation_distanz.distanz_m_diff,
"public".v_can_gesamt_v3_situation_distanz.distanz_m,
"public".v_can_gesamt_v3_situation_distanz.znr_runde,
"public".v_can_gesamt_v3_situation_distanz.runde,
"public".v_can_gesamt_v3_situation_distanz.distanz_runde_m,
"public".v_can_gesamt_v3_situation_distanz.znr_triggerid,
"public".v_can_gesamt_v3_situation_distanz.znr_diff_vp_triggerid,
"public".v_can_gesamt_v3_situation_distanz.triggerid,
"public".v_can_gesamt_v3_situation_distanz.triggerid_v2,
"public".v_can_gesamt_v3_situation_distanz.znr_triggerid_v3,
"public".v_can_gesamt_v3_situation_distanz.triggerid_v3,
"public".v_can_gesamt_v3_situation_distanz.distanz_triggerid_v3_m,
"public".v_can_gesamt_v3_situation_distanz.triggerid_v3_entf_m,
"public".v_can_gesamt_v3_situation_distanz.situation,
"public".v_can_gesamt_v3_situation_distanz.situation_lat,
"public".v_can_gesamt_v3_situation_distanz.situation_long,
"public".v_can_gesamt_v3_situation_distanz.situation_gps_distanz_m,
MIN("public".v_can_gesamt_v3_situation_distanz.situation_gps_distanz_m) 
	OVER (PARTITION BY 
		"public".v_can_gesamt_v3_situation_distanz.vp,
		"public".v_can_gesamt_v3_situation_distanz.runde, 
		"public".v_can_gesamt_v3_situation_distanz.situation) 
	as situation_gps_distanz_min_m,
"public".v_can_gesamt_v3_situation_distanz.geschw_kmh,
"public".v_can_gesamt_v3_situation_distanz.querb_ms2,
"public".v_can_gesamt_v3_situation_distanz.laengsb_ms2,
"public".v_can_gesamt_v3_situation_distanz.gierrate_grad,
"public".v_can_gesamt_v3_situation_distanz.bremsdruck_bar,
"public".v_can_gesamt_v3_situation_distanz.bremsdruck_status,
"public".v_can_gesamt_v3_situation_distanz.lenkradwinkel_grad,
"public".v_can_gesamt_v3_situation_distanz.lenkradwinkel_geschw,
"public".v_can_gesamt_v3_situation_distanz.pedalpos_prozent,
"public".v_can_gesamt_v3_situation_distanz.blinker_links,
"public".v_can_gesamt_v3_situation_distanz.blinker_rechts,
"public".v_can_gesamt_v3_situation_distanz.blinker,
"public".v_can_gesamt_v3_situation_distanz.ldw_seite,
"public".v_can_gesamt_v3_situation_distanz.ldw_tlc_s,
"public".v_can_gesamt_v3_situation_distanz.ldw_dlc_m,
"public".v_can_gesamt_v3_situation_distanz.entf_kreuz_m,
"public".v_can_gesamt_v3_situation_distanz.strtyp,
"public".v_can_gesamt_v3_situation_distanz.anzahl_fahrspuren,
"public".v_can_gesamt_v3_situation_distanz.dgps_korrekturtyp,
"public".v_can_gesamt_v3_situation_distanz.dgps_aufloesungssignal,
"public".v_can_gesamt_v3_situation_distanz.dgps_korrekturalter,
"public".v_can_gesamt_v3_situation_distanz.dgps_zeit_woche,
"public".v_can_gesamt_v3_situation_distanz.dgps_zeit_ms,
"public".v_can_gesamt_v3_situation_distanz.gps_lat,
"public".v_can_gesamt_v3_situation_distanz.gps_lat_dev,
"public".v_can_gesamt_v3_situation_distanz.gps_long,
"public".v_can_gesamt_v3_situation_distanz.gps_long_dev,
"public".v_can_gesamt_v3_situation_distanz.gps_height,
"public".v_can_gesamt_v3_situation_distanz.gps_height_dev
FROM
"public".v_can_gesamt_v3_situation_distanz

ORDER BY "public".v_can_gesamt_v3_situation_distanz.znr