--DROP TABLE IF EXISTS t_can_situation_entf_aggr_v2;
--CREATE TABLE t_can_situation_entf_aggr_v2 AS

DROP TABLE IF EXISTS t_test;
CREATE TABLE t_test AS

SELECT

max("public".t_can_situation_entf_aggr.znr) as znr,
max("public".t_can_situation_entf_aggr.vp) as vp,
max("public".t_can_situation_entf_aggr.zeit_s) as zeit_s,
max("public".t_can_situation_entf_aggr.zeit_s_rounded) as zeit_s_rounded,
max("public".t_can_situation_entf_aggr.distanz_m_diff) as distanz_m_diff,
max("public".t_can_situation_entf_aggr.distanz_m) as distanz_m,
max("public".t_can_situation_entf_aggr.distanz_m_rounded) as distanz_m_rounded,
max("public".t_can_situation_entf_aggr.runde) as runde,
--
CASE 
WHEN max("public".t_can_situation_entf_aggr.runde) = max("public".testdaten.runde_einf) THEN 'einf'
WHEN max("public".t_can_situation_entf_aggr.runde) = max("public".testdaten.runde_normal) THEN 'normal'
WHEN max("public".t_can_situation_entf_aggr.runde) = max("public".testdaten.runde_stress) THEN 'stress'
END AS runde_txt,
--
max("public".t_can_situation_entf_aggr.runde_distanz_m) as runde_distanz_m,
max("public".t_can_situation_entf_aggr.triggerid_v3) as triggerid_v3,
max("public".t_can_situation_entf_aggr.gps_lat) as gps_lat,
max("public".t_can_situation_entf_aggr.gps_long) as gps_long,
max("public".t_can_situation_entf_aggr.situation) as situation,
max("public".t_can_situation_entf_aggr.situation_lat) as situation_lat,
max("public".t_can_situation_entf_aggr.situation_long) as situation_long,
max("public".t_can_situation_entf_aggr.situation_gps_distanz_m) as situation_gps_distanz_m,
max("public".t_can_situation_entf_aggr.situation_gps_distanz_m_min) as situation_gps_distanz_m_min,
max("public".t_can_situation_entf_aggr.zeit_s_situation_max) as zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.zeit_s_situation_max_rounded) as zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.distanz_m_situation_max) as distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.distanz_m_situation_max_rounded) as distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.zeit_s_situation_entf) as zeit_s_situation_entf,
max("public".t_can_situation_entf_aggr.zeit_s_situation_entf_rounded) as zeit_s_situation_entf_rounded,
max("public".t_can_situation_entf_aggr.distanz_m_situation_entf) as distanz_m_situation_entf,
max("public".t_can_situation_entf_aggr.distanz_m_situation_entf_rounded) as distanz_m_situation_entf_rounded,
max("public".t_can_situation_entf_aggr.s01_zeit_s_situation_max) as s01_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s01_zeit_s_situation_max_rounded) as s01_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s01_entf_s) as s01_entf_s,
max("public".t_can_situation_entf_aggr.s01_entf_s_rounded) as s01_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s02_zeit_s_situation_max) as s02_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s02_zeit_s_situation_max_rounded) as s02_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s02_entf_s) as s02_entf_s,
max("public".t_can_situation_entf_aggr.s02_entf_s_rounded) as s02_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s03_zeit_s_situation_max) as s03_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s03_zeit_s_situation_max_rounded) as s03_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s03_entf_s) as s03_entf_s,
max("public".t_can_situation_entf_aggr.s03_entf_s_rounded) as s03_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s04_zeit_s_situation_max) as s04_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s04_zeit_s_situation_max_rounded) as s04_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s04_entf_s) as s04_entf_s,
max("public".t_can_situation_entf_aggr.s04_entf_s_rounded) as s04_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s05_zeit_s_situation_max) as s05_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s05_zeit_s_situation_max_rounded) as s05_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s05_entf_s) as s05_entf_s,
max("public".t_can_situation_entf_aggr.s05_entf_s_rounded) as s05_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s06_zeit_s_situation_max) as s06_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s06_zeit_s_situation_max_rounded) as s06_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s06_entf_s) as s06_entf_s,
max("public".t_can_situation_entf_aggr.s06_entf_s_rounded) as s06_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s07_zeit_s_situation_max) as s07_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s07_zeit_s_situation_max_rounded) as s07_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s07_entf_s) as s07_entf_s,
max("public".t_can_situation_entf_aggr.s07_entf_s_rounded) as s07_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s08_zeit_s_situation_max) as s08_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s08_zeit_s_situation_max_rounded) as s08_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s08_entf_s) as s08_entf_s,
max("public".t_can_situation_entf_aggr.s08_entf_s_rounded) as s08_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s09_zeit_s_situation_max) as s09_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s09_zeit_s_situation_max_rounded) as s09_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s09_entf_s) as s09_entf_s,
max("public".t_can_situation_entf_aggr.s09_entf_s_rounded) as s09_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s10_zeit_s_situation_max) as s10_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s10_zeit_s_situation_max_rounded) as s10_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s10_entf_s) as s10_entf_s,
max("public".t_can_situation_entf_aggr.s10_entf_s_rounded) as s10_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s11_zeit_s_situation_max) as s11_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s11_zeit_s_situation_max_rounded) as s11_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s11_entf_s) as s11_entf_s,
max("public".t_can_situation_entf_aggr.s11_entf_s_rounded) as s11_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s12_zeit_s_situation_max) as s12_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s12_zeit_s_situation_max_rounded) as s12_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s12_entf_s) as s12_entf_s,
max("public".t_can_situation_entf_aggr.s12_entf_s_rounded) as s12_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s13_zeit_s_situation_max) as s13_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s13_zeit_s_situation_max_rounded) as s13_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s13_entf_s) as s13_entf_s,
max("public".t_can_situation_entf_aggr.s13_entf_s_rounded) as s13_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s14_zeit_s_situation_max) as s14_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s14_zeit_s_situation_max_rounded) as s14_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s14_entf_s) as s14_entf_s,
max("public".t_can_situation_entf_aggr.s14_entf_s_rounded) as s14_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s15_zeit_s_situation_max) as s15_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s15_zeit_s_situation_max_rounded) as s15_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s15_entf_s) as s15_entf_s,
max("public".t_can_situation_entf_aggr.s15_entf_s_rounded) as s15_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s16_zeit_s_situation_max) as s16_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s16_zeit_s_situation_max_rounded) as s16_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s16_entf_s) as s16_entf_s,
max("public".t_can_situation_entf_aggr.s16_entf_s_rounded) as s16_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s17_zeit_s_situation_max) as s17_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s17_zeit_s_situation_max_rounded) as s17_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s17_entf_s) as s17_entf_s,
max("public".t_can_situation_entf_aggr.s17_entf_s_rounded) as s17_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s18_zeit_s_situation_max) as s18_zeit_s_situation_max,
max("public".t_can_situation_entf_aggr.s18_zeit_s_situation_max_rounded) as s18_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s18_entf_s) as s18_entf_s,
max("public".t_can_situation_entf_aggr.s18_entf_s_rounded) as s18_entf_s_rounded,
max("public".t_can_situation_entf_aggr.s01_distanz_m_situation_max) as s01_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s01_distanz_m_situation_max_rounded) as s01_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s01_entf_m) as s01_entf_m,
max("public".t_can_situation_entf_aggr.s01_entf_m_rounded) as s01_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s02_distanz_m_situation_max) as s02_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s02_distanz_m_situation_max_rounded) as s02_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s02_entf_m) as s02_entf_m,
max("public".t_can_situation_entf_aggr.s02_entf_m_rounded) as s02_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s03_distanz_m_situation_max) as s03_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s03_distanz_m_situation_max_rounded) as s03_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s03_entf_m) as s03_entf_m,
max("public".t_can_situation_entf_aggr.s03_entf_m_rounded) as s03_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s04_distanz_m_situation_max) as s04_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s04_distanz_m_situation_max_rounded) as s04_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s04_entf_m) as s04_entf_m,
max("public".t_can_situation_entf_aggr.s04_entf_m_rounded) as s04_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s05_distanz_m_situation_max) as s05_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s05_distanz_m_situation_max_rounded) as s05_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s05_entf_m) as s05_entf_m,
max("public".t_can_situation_entf_aggr.s05_entf_m_rounded) as s05_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s06_distanz_m_situation_max) as s06_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s06_distanz_m_situation_max_rounded) as s06_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s06_entf_m) as s06_entf_m,
max("public".t_can_situation_entf_aggr.s06_entf_m_rounded) as s06_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s07_distanz_m_situation_max) as s07_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s07_distanz_m_situation_max_rounded) as s07_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s07_entf_m) as s07_entf_m,
max("public".t_can_situation_entf_aggr.s07_entf_m_rounded) as s07_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s08_distanz_m_situation_max) as s08_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s08_distanz_m_situation_max_rounded) as s08_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s08_entf_m) as s08_entf_m,
max("public".t_can_situation_entf_aggr.s08_entf_m_rounded) as s08_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s09_distanz_m_situation_max) as s09_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s09_distanz_m_situation_max_rounded) as s09_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s09_entf_m) as s09_entf_m,
max("public".t_can_situation_entf_aggr.s09_entf_m_rounded) as s09_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s10_distanz_m_situation_max) as s10_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s10_distanz_m_situation_max_rounded) as s10_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s10_entf_m) as s10_entf_m,
max("public".t_can_situation_entf_aggr.s10_entf_m_rounded) as s10_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s11_distanz_m_situation_max) as s11_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s11_distanz_m_situation_max_rounded) as s11_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s11_entf_m) as s11_entf_m,
max("public".t_can_situation_entf_aggr.s11_entf_m_rounded) as s11_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s12_distanz_m_situation_max) as s12_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s12_distanz_m_situation_max_rounded) as s12_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s12_entf_m) as s12_entf_m,
max("public".t_can_situation_entf_aggr.s12_entf_m_rounded) as s12_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s13_distanz_m_situation_max) as s13_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s13_distanz_m_situation_max_rounded) as s13_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s13_entf_m) as s13_entf_m,
max("public".t_can_situation_entf_aggr.s13_entf_m_rounded) as s13_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s14_distanz_m_situation_max) as s14_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s14_distanz_m_situation_max_rounded) as s14_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s14_entf_m) as s14_entf_m,
max("public".t_can_situation_entf_aggr.s14_entf_m_rounded) as s14_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s15_distanz_m_situation_max) as s15_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s15_distanz_m_situation_max_rounded) as s15_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s15_entf_m) as s15_entf_m,
max("public".t_can_situation_entf_aggr.s15_entf_m_rounded) as s15_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s16_distanz_m_situation_max) as s16_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s16_distanz_m_situation_max_rounded) as s16_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s16_entf_m) as s16_entf_m,
max("public".t_can_situation_entf_aggr.s16_entf_m_rounded) as s16_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s17_distanz_m_situation_max) as s17_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s17_distanz_m_situation_max_rounded) as s17_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s17_entf_m) as s17_entf_m,
max("public".t_can_situation_entf_aggr.s17_entf_m_rounded) as s17_entf_m_rounded,
max("public".t_can_situation_entf_aggr.s18_distanz_m_situation_max) as s18_distanz_m_situation_max,
max("public".t_can_situation_entf_aggr.s18_distanz_m_situation_max_rounded) as s18_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf_aggr.s18_entf_m) as s18_entf_m,
max("public".t_can_situation_entf_aggr.s18_entf_m_rounded) as s18_entf_m_rounded,
max("public".t_can_situation_entf_aggr.geschw_kmh) as geschw_kmh,
max("public".t_can_situation_entf_aggr.geschw_kmh_diff) as geschw_kmh_diff,
max("public".t_can_situation_entf_aggr.querb_ms2) as querb_ms2,
max("public".t_can_situation_entf_aggr.querb_ms2_diff) as querb_ms2_diff,
max("public".t_can_situation_entf_aggr.laengsb_ms2) as laengsb_ms2,
max("public".t_can_situation_entf_aggr.laengsb_ms2_diff) as laengsb_ms2_diff,
max("public".t_can_situation_entf_aggr.gierrate_grad) as gierrate_grad,
max("public".t_can_situation_entf_aggr.gierrate_grad_diff) as gierrate_grad_diff,
max("public".t_can_situation_entf_aggr.bremsdruck_bar) as bremsdruck_bar,
max("public".t_can_situation_entf_aggr.bremsdruck_bar_diff) as bremsdruck_bar_diff,
max("public".t_can_situation_entf_aggr.bremsdruck_status) as bremsdruck_status,
max("public".t_can_situation_entf_aggr.lwi_grad) as lwi_grad,
max("public".t_can_situation_entf_aggr.lwi_grad_diff) as lwi_grad_diff,
max("public".t_can_situation_entf_aggr.lwi_geschw) as lwi_geschw,
max("public".t_can_situation_entf_aggr.lwi_geschw_diff) as lwi_geschw_diff,
max("public".t_can_situation_entf_aggr.pedalpos_prozent) as pedalpos_prozent,
max("public".t_can_situation_entf_aggr.pedalpos_prozent_diff) as pedalpos_prozent_diff,
max("public".t_can_situation_entf_aggr.blinker_links) as blinker_links,
max("public".t_can_situation_entf_aggr.blinker_rechts) as blinker_rechts,
max("public".t_can_situation_entf_aggr.blinker) as blinker,
max("public".t_can_situation_entf_aggr.ldw_seite) as ldw_seite,
max("public".t_can_situation_entf_aggr.ldw_tlc_s) as ldw_tlc_s,
max("public".t_can_situation_entf_aggr.ldw_tlc_s_diff) as ldw_tlc_s_diff,
max("public".t_can_situation_entf_aggr.ldw_dlc_m) as ldw_dlc_m,
max("public".t_can_situation_entf_aggr.ldw_dlc_m_diff) as ldw_dlc_m_diff,
max("public".t_can_situation_entf_aggr.entf_kreuz_m) as entf_kreuz_m,
max("public".t_can_situation_entf_aggr.strtyp) as strtyp,
max("public".t_can_situation_entf_aggr.fahrspuren_anzahl) as fahrspuren_anzahl,
max("public".testdaten.bedingung) as bedingung,
max("public".testdaten.datum) as datum,
max("public".testdaten.versuchsleiter) as versuchsleiter,
max("public".testdaten.datei) as datei


FROM
"public".t_can_situation_entf_aggr
LEFT OUTER JOIN "public".testdaten ON "public".t_can_situation_entf_aggr.vp = "public".testdaten.vp

WHERE "public".t_can_situation_entf_aggr.vp = 27

GROUP BY
"public".t_can_situation_entf_aggr.vp,
--"public".t_can_situation_entf_aggr.runde,
--"public".t_can_situation_entf_aggr.triggerid_v3,
--"public".t_can_situation_entf_aggr.situation,
"public".t_can_situation_entf_aggr.zeit_s_rounded

ORDER BY
"public".t_can_situation_entf_aggr.zeit_s_rounded