CREATE OR REPLACE VIEW test AS

SELECT 
--v_can_gesamt_v2.znr, 
--v_can_gesamt_v2.znr_vp, 
--v_can_gesamt_v2.vp, 
--v_can_gesamt_v2.datei, 
v_can_gesamt_v2.zeit_s, 
v_can_gesamt_v2.geschw_kmh, 
v_can_gesamt_v2.querb_ms2, 
v_can_gesamt_v2.laengsb_ms2, 
v_can_gesamt_v2.gierrate_grad, 
v_can_gesamt_v2.bremsdruck_bar, 
v_can_gesamt_v2.bremsdruck_status, 
v_can_gesamt_v2.lenkradwinkel_grad, 
v_can_gesamt_v2.lenkradwinkel_geschw, 
v_can_gesamt_v2.pedalpos_prozent, 
v_can_gesamt_v2.blinker_links, 
v_can_gesamt_v2.blinker_rechts, 
v_can_gesamt_v2.blinker, 
v_can_gesamt_v2.ldw_seite, 
v_can_gesamt_v2.ldw_tlc_s, 
v_can_gesamt_v2.ldw_dlc_m, 
v_can_gesamt_v2.entf_kreuz_m, 
v_can_gesamt_v2.strtyp, 
v_can_gesamt_v2.anzahl_fahrspuren, 
--v_can_gesamt_v2.dgps_korrekturtyp, 
--v_can_gesamt_v2.dgps_aufloesungssignal, 
--v_can_gesamt_v2.dgps_korrekturalter, 
--v_can_gesamt_v2.dgps_zeit_woche, 
--v_can_gesamt_v2.dgps_zeit_ms, 
v_can_gesamt_v2.gps_lat, 
--v_can_gesamt_v2.gps_lat_dev, 
v_can_gesamt_v2.gps_long, 
--v_can_gesamt_v2.gps_long_dev, 
--v_can_gesamt_v2.gps_height, 
--v_can_gesamt_v2.gps_height_dev, 
--v_can_gesamt_v2.znr_trigger, 
--v_can_gesamt_v2.znr_diff_vp_trigger, 
--v_can_gesamt_v2."trigger", 
v_can_gesamt_v2.trigger_korrigiert, 
v_can_gesamt_v2.trigger_korrigiert_v2
   FROM v_can_gesamt_v2
  WHERE (((v_can_gesamt_v2.vp = (1)::numeric) AND (v_can_gesamt_v2.trigger_korrigiert_v2 >= (6)::numeric)) AND (v_can_gesamt_v2.trigger_korrigiert_v2 <= (8)::numeric));