DROP TABLE IF EXISTS t_can_situation_entf_aggr;
CREATE TABLE t_can_situation_entf_aggr AS

SELECT
max("public".t_can_situation_entf.znr) as znr,
"public".t_can_situation_entf.vp,
max("public".t_can_situation_entf.zeit_s) as zeit_s,
"public".t_can_situation_entf.zeit_s_rounded,
max("public".t_can_situation_entf.distanz_m_diff) as distanz_m_diff,
max("public".t_can_situation_entf.distanz_m) as distanz_m,
max("public".t_can_situation_entf.distanz_m_rounded) as distanz_m_rounded,
"public".t_can_situation_entf.runde,
max("public".t_can_situation_entf.runde_distanz_m) as runde_distanz_m,
"public".t_can_situation_entf.triggerid_v3,
max("public".t_can_situation_entf.gps_lat) as gps_lat,
max("public".t_can_situation_entf.gps_long) as gps_long,
"public".t_can_situation_entf.situation,
max("public".t_can_situation_entf.situation_lat) as situation_lat,
max("public".t_can_situation_entf.situation_long) as situation_long,
max("public".t_can_situation_entf.situation_gps_distanz_m) as situation_gps_distanz_m,
max("public".t_can_situation_entf.situation_gps_distanz_m_min) as situation_gps_distanz_m_min,
max("public".t_can_situation_entf.zeit_s_situation_max) as zeit_s_situation_max,
max("public".t_can_situation_entf.zeit_s_situation_max_rounded) as zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.distanz_m_situation_max) as distanz_m_situation_max,
max("public".t_can_situation_entf.distanz_m_situation_max_rounded) as distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.zeit_s_situation_entf) as zeit_s_situation_entf,
max("public".t_can_situation_entf.zeit_s_situation_entf_rounded) as zeit_s_situation_entf_rounded,
max("public".t_can_situation_entf.distanz_m_situation_entf) as distanz_m_situation_entf,
max("public".t_can_situation_entf.distanz_m_situation_entf_rounded) as distanz_m_situation_entf_rounded,
--
max("public".t_can_situation_entf.s01_zeit_s_situation_max) as s01_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s01_zeit_s_situation_max), 1) as s01_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s01_entf_s) as s01_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s01_zeit_s_situation_max), 1) as s01_entf_s_rounded,
max("public".t_can_situation_entf.s02_zeit_s_situation_max) as s02_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s02_zeit_s_situation_max), 1) as s02_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s02_entf_s) as s02_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s02_zeit_s_situation_max), 1) as s02_entf_s_rounded,
max("public".t_can_situation_entf.s03_zeit_s_situation_max) as s03_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s03_zeit_s_situation_max), 1) as s03_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s03_entf_s) as s03_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s03_zeit_s_situation_max), 1) as s03_entf_s_rounded,
max("public".t_can_situation_entf.s04_zeit_s_situation_max) as s04_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s04_zeit_s_situation_max), 1) as s04_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s04_entf_s) as s04_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s04_zeit_s_situation_max), 1) as s04_entf_s_rounded,
max("public".t_can_situation_entf.s05_zeit_s_situation_max) as s05_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s05_zeit_s_situation_max), 1) as s05_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s05_entf_s) as s05_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s05_zeit_s_situation_max), 1) as s05_entf_s_rounded,
max("public".t_can_situation_entf.s06_zeit_s_situation_max) as s06_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s06_zeit_s_situation_max), 1) as s06_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s06_entf_s) as s06_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s06_zeit_s_situation_max), 1) as s06_entf_s_rounded,
max("public".t_can_situation_entf.s07_zeit_s_situation_max) as s07_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s07_zeit_s_situation_max), 1) as s07_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s07_entf_s) as s07_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s07_zeit_s_situation_max), 1) as s07_entf_s_rounded,
max("public".t_can_situation_entf.s08_zeit_s_situation_max) as s08_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s08_zeit_s_situation_max), 1) as s08_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s08_entf_s) as s08_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s08_zeit_s_situation_max), 1) as s08_entf_s_rounded,
max("public".t_can_situation_entf.s09_zeit_s_situation_max) as s09_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s09_zeit_s_situation_max), 1) as s09_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s09_entf_s) as s09_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s09_zeit_s_situation_max), 1) as s09_entf_s_rounded,
max("public".t_can_situation_entf.s10_zeit_s_situation_max) as s10_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s10_zeit_s_situation_max), 1) as s10_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s10_entf_s) as s10_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s10_zeit_s_situation_max), 1) as s10_entf_s_rounded,
max("public".t_can_situation_entf.s11_zeit_s_situation_max) as s11_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s11_zeit_s_situation_max), 1) as s11_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s11_entf_s) as s11_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s11_zeit_s_situation_max), 1) as s11_entf_s_rounded,
max("public".t_can_situation_entf.s12_zeit_s_situation_max) as s12_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s12_zeit_s_situation_max), 1) as s12_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s12_entf_s) as s12_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s12_zeit_s_situation_max), 1) as s12_entf_s_rounded,
max("public".t_can_situation_entf.s13_zeit_s_situation_max) as s13_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s13_zeit_s_situation_max), 1) as s13_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s13_entf_s) as s13_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s13_zeit_s_situation_max), 1) as s13_entf_s_rounded,
max("public".t_can_situation_entf.s14_zeit_s_situation_max) as s14_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s14_zeit_s_situation_max), 1) as s14_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s14_entf_s) as s14_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s14_zeit_s_situation_max), 1) as s14_entf_s_rounded,
max("public".t_can_situation_entf.s15_zeit_s_situation_max) as s15_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s15_zeit_s_situation_max), 1) as s15_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s15_entf_s) as s15_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s15_zeit_s_situation_max), 1) as s15_entf_s_rounded,
max("public".t_can_situation_entf.s16_zeit_s_situation_max) as s16_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s16_zeit_s_situation_max), 1) as s16_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s16_entf_s) as s16_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s16_zeit_s_situation_max), 1) as s16_entf_s_rounded,
max("public".t_can_situation_entf.s17_zeit_s_situation_max) as s17_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s17_zeit_s_situation_max), 1) as s17_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s17_entf_s) as s17_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s17_zeit_s_situation_max), 1) as s17_entf_s_rounded,
max("public".t_can_situation_entf.s18_zeit_s_situation_max) as s18_zeit_s_situation_max,
round(max("public".t_can_situation_entf.s18_zeit_s_situation_max), 1) as s18_zeit_s_situation_max_rounded,
max("public".t_can_situation_entf.s18_entf_s) as s18_entf_s,
"public".t_can_situation_entf.zeit_s_rounded - round(max("public".t_can_situation_entf.s18_zeit_s_situation_max), 1) as s18_entf_s_rounded,
--
max("public".t_can_situation_entf.s01_distanz_m_situation_max) as s01_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s01_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s01_entf_m) as s01_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s01_entf_m_rounded,
max("public".t_can_situation_entf.s02_distanz_m_situation_max) as s02_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s02_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s02_entf_m) as s02_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s02_distanz_m_situation_max), 0) as s02_entf_m_rounded,
max("public".t_can_situation_entf.s03_distanz_m_situation_max) as s03_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s03_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s03_entf_m) as s03_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s03_distanz_m_situation_max), 0) as s03_entf_m_rounded,
max("public".t_can_situation_entf.s04_distanz_m_situation_max) as s04_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s04_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s04_entf_m) as s04_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s04_distanz_m_situation_max), 0) as s04_entf_m_rounded,
max("public".t_can_situation_entf.s05_distanz_m_situation_max) as s05_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s05_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s05_entf_m) as s05_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s05_distanz_m_situation_max), 0) as s05_entf_m_rounded,
max("public".t_can_situation_entf.s06_distanz_m_situation_max) as s06_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s06_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s06_entf_m) as s06_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s06_distanz_m_situation_max), 0) as s06_entf_m_rounded,
max("public".t_can_situation_entf.s07_distanz_m_situation_max) as s07_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s07_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s07_entf_m) as s07_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s07_distanz_m_situation_max), 0) as s07_entf_m_rounded,
max("public".t_can_situation_entf.s08_distanz_m_situation_max) as s08_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s08_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s08_entf_m) as s08_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s08_distanz_m_situation_max), 0) as s08_entf_m_rounded,
max("public".t_can_situation_entf.s09_distanz_m_situation_max) as s09_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s09_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s09_entf_m) as s09_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s09_distanz_m_situation_max), 0) as s09_entf_m_rounded,
max("public".t_can_situation_entf.s10_distanz_m_situation_max) as s10_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s10_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s10_entf_m) as s10_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s10_distanz_m_situation_max), 0) as s10_entf_m_rounded,
max("public".t_can_situation_entf.s11_distanz_m_situation_max) as s11_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s11_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s11_entf_m) as s11_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s11_distanz_m_situation_max), 0) as s11_entf_m_rounded,
max("public".t_can_situation_entf.s12_distanz_m_situation_max) as s12_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s12_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s12_entf_m) as s12_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s12_distanz_m_situation_max), 0) as s12_entf_m_rounded,
max("public".t_can_situation_entf.s13_distanz_m_situation_max) as s13_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s13_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s13_entf_m) as s13_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s13_distanz_m_situation_max), 0) as s13_entf_m_rounded,
max("public".t_can_situation_entf.s14_distanz_m_situation_max) as s14_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s14_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s14_entf_m) as s14_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s14_distanz_m_situation_max), 0) as s14_entf_m_rounded,
max("public".t_can_situation_entf.s15_distanz_m_situation_max) as s15_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s15_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s15_entf_m) as s15_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s15_distanz_m_situation_max), 0) as s15_entf_m_rounded,
max("public".t_can_situation_entf.s16_distanz_m_situation_max) as s16_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s16_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s16_entf_m) as s16_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s16_distanz_m_situation_max), 0) as s16_entf_m_rounded,
max("public".t_can_situation_entf.s17_distanz_m_situation_max) as s17_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s17_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s17_entf_m) as s17_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s17_distanz_m_situation_max), 0) as s17_entf_m_rounded,
max("public".t_can_situation_entf.s18_distanz_m_situation_max) as s18_distanz_m_situation_max,
round(max("public".t_can_situation_entf.s01_distanz_m_situation_max), 0) as s18_distanz_m_situation_max_rounded,
max("public".t_can_situation_entf.s18_entf_m) as s18_entf_m,
max("public".t_can_situation_entf.distanz_m_rounded) - round(max("public".t_can_situation_entf.s18_distanz_m_situation_max), 0) as s18_entf_m_rounded,
--
max("public".t_can_situation_entf.geschw_kmh) as geschw_kmh,
max("public".t_can_situation_entf.geschw_kmh_diff) as geschw_kmh_diff,
max("public".t_can_situation_entf.querb_ms2) as querb_ms2,
max("public".t_can_situation_entf.querb_ms2_diff) as querb_ms2_diff,
max("public".t_can_situation_entf.laengsb_ms2) as laengsb_ms2,
max("public".t_can_situation_entf.laengsb_ms2_diff) as laengsb_ms2_diff,
max("public".t_can_situation_entf.gierrate_grad) as gierrate_grad,
max("public".t_can_situation_entf.gierrate_grad_diff) as gierrate_grad_diff,
max("public".t_can_situation_entf.bremsdruck_bar) as bremsdruck_bar,
max("public".t_can_situation_entf.bremsdruck_bar_diff) as bremsdruck_bar_diff,
max("public".t_can_situation_entf.bremsdruck_status) as bremsdruck_status,
max("public".t_can_situation_entf.lwi_grad) as lwi_grad,
max("public".t_can_situation_entf.lwi_grad_diff) as lwi_grad_diff,
max("public".t_can_situation_entf.lwi_geschw) as lwi_geschw,
max("public".t_can_situation_entf.lwi_geschw_diff) as lwi_geschw_diff,
max("public".t_can_situation_entf.pedalpos_prozent) as pedalpos_prozent,
max("public".t_can_situation_entf.pedalpos_prozent_diff) as pedalpos_prozent_diff,
max("public".t_can_situation_entf.blinker_links) as blinker_links,
max("public".t_can_situation_entf.blinker_rechts) as blinker_rechts,
max("public".t_can_situation_entf.blinker) as blinker,
max("public".t_can_situation_entf.ldw_seite) as ldw_seite,
max("public".t_can_situation_entf.ldw_tlc_s) as ldw_tlc_s,
max("public".t_can_situation_entf.ldw_tlc_s_diff) as ldw_tlc_s_diff,
max("public".t_can_situation_entf.ldw_dlc_m) as ldw_dlc_m,
max("public".t_can_situation_entf.ldw_dlc_m_diff) as ldw_dlc_m_diff,
max("public".t_can_situation_entf.entf_kreuz_m) as entf_kreuz_m,
max("public".t_can_situation_entf.strtyp) as strtyp,
max("public".t_can_situation_entf.fahrspuren_anzahl) as fahrspuren_anzahl
FROM
"public".t_can_situation_entf
GROUP BY
"public".t_can_situation_entf.vp,
"public".t_can_situation_entf.runde,
"public".t_can_situation_entf.triggerid_v3,
"public".t_can_situation_entf.situation,
"public".t_can_situation_entf.zeit_s_rounded
ORDER BY
max("public".t_can_situation_entf.znr)