DROP TABLE IF EXISTS t_can_full_aggr_dist_m_rnd0_min1 CASCADE;
CREATE TABLE t_can_full_aggr_dist_m_rnd0_min1 AS

SELECT

min("public".t_can_full1.rownr) as rownr,
row_number() over (partition by "public".t_can_full1.subid, "public".t_can_full1.dist_m_rnd0 order by min("public".t_can_full1.rownr)) as rownr_aggr,
"public".t_can_full1.subid,
min("public".t_can_full1.time_s) as time_s,
min("public".t_can_full1.time_s_rnd0) as time_s_rnd0,
min("public".t_can_full1.time_s_rnd1) as time_s_rnd1,
min("public".t_can_full1.dist_m_diff) as dist_m_diff,
min("public".t_can_full1.dist_m) as dist_m,
"public".t_can_full1.dist_m_rnd0,
min("public".t_can_full1.dist_m_rnd1) as dist_m_rnd1,
min("public".t_can_full1.round) as round,
"public".t_can_full1.round_txt,
min("public".t_can_full1.round_dist_m) as round_dist_m,
min("public".t_can_full1.round_dist_m_rnd0) as round_dist_m_rnd0,
min("public".t_can_full1.round_dist_m_rnd1) as round_dist_m_rnd1,
min("public".t_can_full1.gps_lat) as gps_lat,
min("public".t_can_full1.gps_long) as gps_long,
--
min("public".t_can_full1.s01_gps_lat) as s01_gps_lat,
min("public".t_can_full1.s01_gps_long) as s01_gps_long,
min("public".t_can_full1.s02_gps_lat) as s02_gps_lat,
min("public".t_can_full1.s02_gps_long) as s02_gps_long,
min("public".t_can_full1.s03_gps_lat) as s03_gps_lat,
min("public".t_can_full1.s03_gps_long) as s03_gps_long,
min("public".t_can_full1.s04_gps_lat) as s04_gps_lat,
min("public".t_can_full1.s04_gps_long) as s04_gps_long,
min("public".t_can_full1.s05_gps_lat) as s05_gps_lat,
min("public".t_can_full1.s05_gps_long) as s05_gps_long,
min("public".t_can_full1.s06_gps_lat) as s06_gps_lat,
min("public".t_can_full1.s06_gps_long) as s06_gps_long,
min("public".t_can_full1.s07_gps_lat) as s07_gps_lat,
min("public".t_can_full1.s07_gps_long) as s07_gps_long,
min("public".t_can_full1.s08_gps_lat) as s08_gps_lat,
min("public".t_can_full1.s08_gps_long) as s08_gps_long,
min("public".t_can_full1.s09_gps_lat) as s09_gps_lat,
min("public".t_can_full1.s09_gps_long) as s09_gps_long,
min("public".t_can_full1.s10_gps_lat) as s10_gps_lat,
min("public".t_can_full1.s10_gps_long) as s10_gps_long,
min("public".t_can_full1.s11_gps_lat) as s11_gps_lat,
min("public".t_can_full1.s11_gps_long) as s11_gps_long,
min("public".t_can_full1.s12_gps_lat) as s12_gps_lat,
min("public".t_can_full1.s12_gps_long) as s12_gps_long,
min("public".t_can_full1.s13_gps_lat) as s13_gps_lat,
min("public".t_can_full1.s13_gps_long) as s13_gps_long,
min("public".t_can_full1.s14_gps_lat) as s14_gps_lat,
min("public".t_can_full1.s14_gps_long) as s14_gps_long,
min("public".t_can_full1.s15_gps_lat) as s15_gps_lat,
min("public".t_can_full1.s15_gps_long) as s15_gps_long,
min("public".t_can_full1.s16_gps_lat) as s16_gps_lat,
min("public".t_can_full1.s16_gps_long) as s16_gps_long,
min("public".t_can_full1.s17_gps_lat) as s17_gps_lat,
min("public".t_can_full1.s17_gps_long) as s17_gps_long,
min("public".t_can_full1.s18_gps_lat) as s18_gps_lat,
min("public".t_can_full1.s18_gps_long) as s18_gps_long,
--
min("public".t_can_full1.s01_gps_dist_m) as s01_gps_dist_m,
min("public".t_can_full1.s02_gps_dist_m) as s02_gps_dist_m,
min("public".t_can_full1.s03_gps_dist_m) as s03_gps_dist_m,
min("public".t_can_full1.s04_gps_dist_m) as s04_gps_dist_m,
min("public".t_can_full1.s05_gps_dist_m) as s05_gps_dist_m,
min("public".t_can_full1.s06_gps_dist_m) as s06_gps_dist_m,
min("public".t_can_full1.s07_gps_dist_m) as s07_gps_dist_m,
min("public".t_can_full1.s08_gps_dist_m) as s08_gps_dist_m,
min("public".t_can_full1.s09_gps_dist_m) as s09_gps_dist_m,
min("public".t_can_full1.s10_gps_dist_m) as s10_gps_dist_m,
min("public".t_can_full1.s11_gps_dist_m) as s11_gps_dist_m,
min("public".t_can_full1.s12_gps_dist_m) as s12_gps_dist_m,
min("public".t_can_full1.s13_gps_dist_m) as s13_gps_dist_m,
min("public".t_can_full1.s14_gps_dist_m) as s14_gps_dist_m,
min("public".t_can_full1.s15_gps_dist_m) as s15_gps_dist_m,
min("public".t_can_full1.s16_gps_dist_m) as s16_gps_dist_m,
min("public".t_can_full1.s17_gps_dist_m) as s17_gps_dist_m,
min("public".t_can_full1.s18_gps_dist_m) as s18_gps_dist_m,
--
min("public".t_can_full1.s01_gps_dist_m_min) as s01_gps_dist_m_min,
min("public".t_can_full1.s02_gps_dist_m_min) as s02_gps_dist_m_min,
min("public".t_can_full1.s03_gps_dist_m_min) as s03_gps_dist_m_min,
min("public".t_can_full1.s04_gps_dist_m_min) as s04_gps_dist_m_min,
min("public".t_can_full1.s05_gps_dist_m_min) as s05_gps_dist_m_min,
min("public".t_can_full1.s06_gps_dist_m_min) as s06_gps_dist_m_min,
min("public".t_can_full1.s07_gps_dist_m_min) as s07_gps_dist_m_min,
min("public".t_can_full1.s08_gps_dist_m_min) as s08_gps_dist_m_min,
min("public".t_can_full1.s09_gps_dist_m_min) as s09_gps_dist_m_min,
min("public".t_can_full1.s10_gps_dist_m_min) as s10_gps_dist_m_min,
min("public".t_can_full1.s11_gps_dist_m_min) as s11_gps_dist_m_min,
min("public".t_can_full1.s12_gps_dist_m_min) as s12_gps_dist_m_min,
min("public".t_can_full1.s13_gps_dist_m_min) as s13_gps_dist_m_min,
min("public".t_can_full1.s14_gps_dist_m_min) as s14_gps_dist_m_min,
min("public".t_can_full1.s15_gps_dist_m_min) as s15_gps_dist_m_min,
min("public".t_can_full1.s16_gps_dist_m_min) as s16_gps_dist_m_min,
min("public".t_can_full1.s17_gps_dist_m_min) as s17_gps_dist_m_min,
min("public".t_can_full1.s18_gps_dist_m_min) as s18_gps_dist_m_min,
--
min("public".t_can_full1.s01_time_s_min) as s01_time_s_min,
min("public".t_can_full1.s02_time_s_min) as s02_time_s_min,
min("public".t_can_full1.s03_time_s_min) as s03_time_s_min,
min("public".t_can_full1.s04_time_s_min) as s04_time_s_min,
min("public".t_can_full1.s05_time_s_min) as s05_time_s_min,
min("public".t_can_full1.s06_time_s_min) as s06_time_s_min,
min("public".t_can_full1.s07_time_s_min) as s07_time_s_min,
min("public".t_can_full1.s08_time_s_min) as s08_time_s_min,
min("public".t_can_full1.s09_time_s_min) as s09_time_s_min,
min("public".t_can_full1.s10_time_s_min) as s10_time_s_min,
min("public".t_can_full1.s11_time_s_min) as s11_time_s_min,
min("public".t_can_full1.s12_time_s_min) as s12_time_s_min,
min("public".t_can_full1.s13_time_s_min) as s13_time_s_min,
min("public".t_can_full1.s14_time_s_min) as s14_time_s_min,
min("public".t_can_full1.s15_time_s_min) as s15_time_s_min,
min("public".t_can_full1.s16_time_s_min) as s16_time_s_min,
min("public".t_can_full1.s17_time_s_min) as s17_time_s_min,
min("public".t_can_full1.s18_time_s_min) as s18_time_s_min,
--
round(min("public".t_can_full1.s01_time_s_min), 0) as s01_time_s_min_rnd0,
round(min("public".t_can_full1.s02_time_s_min), 0) as s02_time_s_min_rnd0,
round(min("public".t_can_full1.s03_time_s_min), 0) as s03_time_s_min_rnd0,
round(min("public".t_can_full1.s04_time_s_min), 0) as s04_time_s_min_rnd0,
round(min("public".t_can_full1.s05_time_s_min), 0) as s05_time_s_min_rnd0,
round(min("public".t_can_full1.s06_time_s_min), 0) as s06_time_s_min_rnd0,
round(min("public".t_can_full1.s07_time_s_min), 0) as s07_time_s_min_rnd0,
round(min("public".t_can_full1.s08_time_s_min), 0) as s08_time_s_min_rnd0,
round(min("public".t_can_full1.s09_time_s_min), 0) as s09_time_s_min_rnd0,
round(min("public".t_can_full1.s10_time_s_min), 0) as s10_time_s_min_rnd0,
round(min("public".t_can_full1.s11_time_s_min), 0) as s11_time_s_min_rnd0,
round(min("public".t_can_full1.s12_time_s_min), 0) as s12_time_s_min_rnd0,
round(min("public".t_can_full1.s13_time_s_min), 0) as s13_time_s_min_rnd0,
round(min("public".t_can_full1.s14_time_s_min), 0) as s14_time_s_min_rnd0,
round(min("public".t_can_full1.s15_time_s_min), 0) as s15_time_s_min_rnd0,
round(min("public".t_can_full1.s16_time_s_min), 0) as s16_time_s_min_rnd0,
round(min("public".t_can_full1.s17_time_s_min), 0) as s17_time_s_min_rnd0,
round(min("public".t_can_full1.s18_time_s_min), 0) as s18_time_s_min_rnd0,
--
round(min("public".t_can_full1.s01_time_s_min), 1) as s01_time_s_min_rnd1,
round(min("public".t_can_full1.s02_time_s_min), 1) as s02_time_s_min_rnd1,
round(min("public".t_can_full1.s03_time_s_min), 1) as s03_time_s_min_rnd1,
round(min("public".t_can_full1.s04_time_s_min), 1) as s04_time_s_min_rnd1,
round(min("public".t_can_full1.s05_time_s_min), 1) as s05_time_s_min_rnd1,
round(min("public".t_can_full1.s06_time_s_min), 1) as s06_time_s_min_rnd1,
round(min("public".t_can_full1.s07_time_s_min), 1) as s07_time_s_min_rnd1,
round(min("public".t_can_full1.s08_time_s_min), 1) as s08_time_s_min_rnd1,
round(min("public".t_can_full1.s09_time_s_min), 1) as s09_time_s_min_rnd1,
round(min("public".t_can_full1.s10_time_s_min), 1) as s10_time_s_min_rnd1,
round(min("public".t_can_full1.s11_time_s_min), 1) as s11_time_s_min_rnd1,
round(min("public".t_can_full1.s12_time_s_min), 1) as s12_time_s_min_rnd1,
round(min("public".t_can_full1.s13_time_s_min), 1) as s13_time_s_min_rnd1,
round(min("public".t_can_full1.s14_time_s_min), 1) as s14_time_s_min_rnd1,
round(min("public".t_can_full1.s15_time_s_min), 1) as s15_time_s_min_rnd1,
round(min("public".t_can_full1.s16_time_s_min), 1) as s16_time_s_min_rnd1,
round(min("public".t_can_full1.s17_time_s_min), 1) as s17_time_s_min_rnd1,
round(min("public".t_can_full1.s18_time_s_min), 1) as s18_time_s_min_rnd1,
--
min("public".t_can_full1.s01_dist_m_min) as s01_dist_m_min,
min("public".t_can_full1.s02_dist_m_min) as s02_dist_m_min,
min("public".t_can_full1.s03_dist_m_min) as s03_dist_m_min,
min("public".t_can_full1.s04_dist_m_min) as s04_dist_m_min,
min("public".t_can_full1.s05_dist_m_min) as s05_dist_m_min,
min("public".t_can_full1.s06_dist_m_min) as s06_dist_m_min,
min("public".t_can_full1.s07_dist_m_min) as s07_dist_m_min,
min("public".t_can_full1.s08_dist_m_min) as s08_dist_m_min,
min("public".t_can_full1.s09_dist_m_min) as s09_dist_m_min,
min("public".t_can_full1.s10_dist_m_min) as s10_dist_m_min,
min("public".t_can_full1.s11_dist_m_min) as s11_dist_m_min,
min("public".t_can_full1.s12_dist_m_min) as s12_dist_m_min,
min("public".t_can_full1.s13_dist_m_min) as s13_dist_m_min,
min("public".t_can_full1.s14_dist_m_min) as s14_dist_m_min,
min("public".t_can_full1.s15_dist_m_min) as s15_dist_m_min,
min("public".t_can_full1.s16_dist_m_min) as s16_dist_m_min,
min("public".t_can_full1.s17_dist_m_min) as s17_dist_m_min,
min("public".t_can_full1.s18_dist_m_min) as s18_dist_m_min,
--
round(min("public".t_can_full1.s01_dist_m_min), 0) as s01_dist_m_min_rnd0,
round(min("public".t_can_full1.s02_dist_m_min), 0) as s02_dist_m_min_rnd0,
round(min("public".t_can_full1.s03_dist_m_min), 0) as s03_dist_m_min_rnd0,
round(min("public".t_can_full1.s04_dist_m_min), 0) as s04_dist_m_min_rnd0,
round(min("public".t_can_full1.s05_dist_m_min), 0) as s05_dist_m_min_rnd0,
round(min("public".t_can_full1.s06_dist_m_min), 0) as s06_dist_m_min_rnd0,
round(min("public".t_can_full1.s07_dist_m_min), 0) as s07_dist_m_min_rnd0,
round(min("public".t_can_full1.s08_dist_m_min), 0) as s08_dist_m_min_rnd0,
round(min("public".t_can_full1.s09_dist_m_min), 0) as s09_dist_m_min_rnd0,
round(min("public".t_can_full1.s10_dist_m_min), 0) as s10_dist_m_min_rnd0,
round(min("public".t_can_full1.s11_dist_m_min), 0) as s11_dist_m_min_rnd0,
round(min("public".t_can_full1.s12_dist_m_min), 0) as s12_dist_m_min_rnd0,
round(min("public".t_can_full1.s13_dist_m_min), 0) as s13_dist_m_min_rnd0,
round(min("public".t_can_full1.s14_dist_m_min), 0) as s14_dist_m_min_rnd0,
round(min("public".t_can_full1.s15_dist_m_min), 0) as s15_dist_m_min_rnd0,
round(min("public".t_can_full1.s16_dist_m_min), 0) as s16_dist_m_min_rnd0,
round(min("public".t_can_full1.s17_dist_m_min), 0) as s17_dist_m_min_rnd0,
round(min("public".t_can_full1.s18_dist_m_min), 0) as s18_dist_m_min_rnd0,
--
round(min("public".t_can_full1.s01_dist_m_min), 1) as s01_dist_m_min_rnd1,
round(min("public".t_can_full1.s02_dist_m_min), 1) as s02_dist_m_min_rnd1,
round(min("public".t_can_full1.s03_dist_m_min), 1) as s03_dist_m_min_rnd1,
round(min("public".t_can_full1.s04_dist_m_min), 1) as s04_dist_m_min_rnd1,
round(min("public".t_can_full1.s05_dist_m_min), 1) as s05_dist_m_min_rnd1,
round(min("public".t_can_full1.s06_dist_m_min), 1) as s06_dist_m_min_rnd1,
round(min("public".t_can_full1.s07_dist_m_min), 1) as s07_dist_m_min_rnd1,
round(min("public".t_can_full1.s08_dist_m_min), 1) as s08_dist_m_min_rnd1,
round(min("public".t_can_full1.s09_dist_m_min), 1) as s09_dist_m_min_rnd1,
round(min("public".t_can_full1.s10_dist_m_min), 1) as s10_dist_m_min_rnd1,
round(min("public".t_can_full1.s11_dist_m_min), 1) as s11_dist_m_min_rnd1,
round(min("public".t_can_full1.s12_dist_m_min), 1) as s12_dist_m_min_rnd1,
round(min("public".t_can_full1.s13_dist_m_min), 1) as s13_dist_m_min_rnd1,
round(min("public".t_can_full1.s14_dist_m_min), 1) as s14_dist_m_min_rnd1,
round(min("public".t_can_full1.s15_dist_m_min), 1) as s15_dist_m_min_rnd1,
round(min("public".t_can_full1.s16_dist_m_min), 1) as s16_dist_m_min_rnd1,
round(min("public".t_can_full1.s17_dist_m_min), 1) as s17_dist_m_min_rnd1,
round(min("public".t_can_full1.s18_dist_m_min), 1) as s18_dist_m_min_rnd1,
--
min("public".t_can_full1.s01_dist_s) as s01_dist_s,
min("public".t_can_full1.s02_dist_s) as s02_dist_s,
min("public".t_can_full1.s03_dist_s) as s03_dist_s,
min("public".t_can_full1.s04_dist_s) as s04_dist_s,
min("public".t_can_full1.s05_dist_s) as s05_dist_s,
min("public".t_can_full1.s06_dist_s) as s06_dist_s,
min("public".t_can_full1.s07_dist_s) as s07_dist_s,
min("public".t_can_full1.s08_dist_s) as s08_dist_s,
min("public".t_can_full1.s09_dist_s) as s09_dist_s,
min("public".t_can_full1.s10_dist_s) as s10_dist_s,
min("public".t_can_full1.s11_dist_s) as s11_dist_s,
min("public".t_can_full1.s12_dist_s) as s12_dist_s,
min("public".t_can_full1.s13_dist_s) as s13_dist_s,
min("public".t_can_full1.s14_dist_s) as s14_dist_s,
min("public".t_can_full1.s15_dist_s) as s15_dist_s,
min("public".t_can_full1.s16_dist_s) as s16_dist_s,
min("public".t_can_full1.s17_dist_s) as s17_dist_s,
min("public".t_can_full1.s18_dist_s) as s18_dist_s,
--
min("public".t_can_full1.s01_dist_s_rnd0) as s01_dist_s_rnd0,
min("public".t_can_full1.s02_dist_s_rnd0) as s02_dist_s_rnd0,
min("public".t_can_full1.s03_dist_s_rnd0) as s03_dist_s_rnd0,
min("public".t_can_full1.s04_dist_s_rnd0) as s04_dist_s_rnd0,
min("public".t_can_full1.s05_dist_s_rnd0) as s05_dist_s_rnd0,
min("public".t_can_full1.s06_dist_s_rnd0) as s06_dist_s_rnd0,
min("public".t_can_full1.s07_dist_s_rnd0) as s07_dist_s_rnd0,
min("public".t_can_full1.s08_dist_s_rnd0) as s08_dist_s_rnd0,
min("public".t_can_full1.s09_dist_s_rnd0) as s09_dist_s_rnd0,
min("public".t_can_full1.s10_dist_s_rnd0) as s10_dist_s_rnd0,
min("public".t_can_full1.s11_dist_s_rnd0) as s11_dist_s_rnd0,
min("public".t_can_full1.s12_dist_s_rnd0) as s12_dist_s_rnd0,
min("public".t_can_full1.s13_dist_s_rnd0) as s13_dist_s_rnd0,
min("public".t_can_full1.s14_dist_s_rnd0) as s14_dist_s_rnd0,
min("public".t_can_full1.s15_dist_s_rnd0) as s15_dist_s_rnd0,
min("public".t_can_full1.s16_dist_s_rnd0) as s16_dist_s_rnd0,
min("public".t_can_full1.s17_dist_s_rnd0) as s17_dist_s_rnd0,
min("public".t_can_full1.s18_dist_s_rnd0) as s18_dist_s_rnd0,
--
min("public".t_can_full1.s01_dist_s_rnd1) as s01_dist_s_rnd1,
min("public".t_can_full1.s02_dist_s_rnd1) as s02_dist_s_rnd1,
min("public".t_can_full1.s03_dist_s_rnd1) as s03_dist_s_rnd1,
min("public".t_can_full1.s04_dist_s_rnd1) as s04_dist_s_rnd1,
min("public".t_can_full1.s05_dist_s_rnd1) as s05_dist_s_rnd1,
min("public".t_can_full1.s06_dist_s_rnd1) as s06_dist_s_rnd1,
min("public".t_can_full1.s07_dist_s_rnd1) as s07_dist_s_rnd1,
min("public".t_can_full1.s08_dist_s_rnd1) as s08_dist_s_rnd1,
min("public".t_can_full1.s09_dist_s_rnd1) as s09_dist_s_rnd1,
min("public".t_can_full1.s10_dist_s_rnd1) as s10_dist_s_rnd1,
min("public".t_can_full1.s11_dist_s_rnd1) as s11_dist_s_rnd1,
min("public".t_can_full1.s12_dist_s_rnd1) as s12_dist_s_rnd1,
min("public".t_can_full1.s13_dist_s_rnd1) as s13_dist_s_rnd1,
min("public".t_can_full1.s14_dist_s_rnd1) as s14_dist_s_rnd1,
min("public".t_can_full1.s15_dist_s_rnd1) as s15_dist_s_rnd1,
min("public".t_can_full1.s16_dist_s_rnd1) as s16_dist_s_rnd1,
min("public".t_can_full1.s17_dist_s_rnd1) as s17_dist_s_rnd1,
min("public".t_can_full1.s18_dist_s_rnd1) as s18_dist_s_rnd1,
--
min("public".t_can_full1.s01_dist_m) as s01_dist_m,
min("public".t_can_full1.s02_dist_m) as s02_dist_m,
min("public".t_can_full1.s03_dist_m) as s03_dist_m,
min("public".t_can_full1.s04_dist_m) as s04_dist_m,
min("public".t_can_full1.s05_dist_m) as s05_dist_m,
min("public".t_can_full1.s06_dist_m) as s06_dist_m,
min("public".t_can_full1.s07_dist_m) as s07_dist_m,
min("public".t_can_full1.s08_dist_m) as s08_dist_m,
min("public".t_can_full1.s09_dist_m) as s09_dist_m,
min("public".t_can_full1.s10_dist_m) as s10_dist_m,
min("public".t_can_full1.s11_dist_m) as s11_dist_m,
min("public".t_can_full1.s12_dist_m) as s12_dist_m,
min("public".t_can_full1.s13_dist_m) as s13_dist_m,
min("public".t_can_full1.s14_dist_m) as s14_dist_m,
min("public".t_can_full1.s15_dist_m) as s15_dist_m,
min("public".t_can_full1.s16_dist_m) as s16_dist_m,
min("public".t_can_full1.s17_dist_m) as s17_dist_m,
min("public".t_can_full1.s18_dist_m) as s18_dist_m,
--
min("public".t_can_full1.s01_dist_m_rnd0) as s01_dist_m_rnd0,
min("public".t_can_full1.s02_dist_m_rnd0) as s02_dist_m_rnd0,
min("public".t_can_full1.s03_dist_m_rnd0) as s03_dist_m_rnd0,
min("public".t_can_full1.s04_dist_m_rnd0) as s04_dist_m_rnd0,
min("public".t_can_full1.s05_dist_m_rnd0) as s05_dist_m_rnd0,
min("public".t_can_full1.s06_dist_m_rnd0) as s06_dist_m_rnd0,
min("public".t_can_full1.s07_dist_m_rnd0) as s07_dist_m_rnd0,
min("public".t_can_full1.s08_dist_m_rnd0) as s08_dist_m_rnd0,
min("public".t_can_full1.s09_dist_m_rnd0) as s09_dist_m_rnd0,
min("public".t_can_full1.s10_dist_m_rnd0) as s10_dist_m_rnd0,
min("public".t_can_full1.s11_dist_m_rnd0) as s11_dist_m_rnd0,
min("public".t_can_full1.s12_dist_m_rnd0) as s12_dist_m_rnd0,
min("public".t_can_full1.s13_dist_m_rnd0) as s13_dist_m_rnd0,
min("public".t_can_full1.s14_dist_m_rnd0) as s14_dist_m_rnd0,
min("public".t_can_full1.s15_dist_m_rnd0) as s15_dist_m_rnd0,
min("public".t_can_full1.s16_dist_m_rnd0) as s16_dist_m_rnd0,
min("public".t_can_full1.s17_dist_m_rnd0) as s17_dist_m_rnd0,
min("public".t_can_full1.s18_dist_m_rnd0) as s18_dist_m_rnd0,
--
min("public".t_can_full1.s01_dist_m_rnd1) as s01_dist_m_rnd1,
min("public".t_can_full1.s02_dist_m_rnd1) as s02_dist_m_rnd1,
min("public".t_can_full1.s03_dist_m_rnd1) as s03_dist_m_rnd1,
min("public".t_can_full1.s04_dist_m_rnd1) as s04_dist_m_rnd1,
min("public".t_can_full1.s05_dist_m_rnd1) as s05_dist_m_rnd1,
min("public".t_can_full1.s06_dist_m_rnd1) as s06_dist_m_rnd1,
min("public".t_can_full1.s07_dist_m_rnd1) as s07_dist_m_rnd1,
min("public".t_can_full1.s08_dist_m_rnd1) as s08_dist_m_rnd1,
min("public".t_can_full1.s09_dist_m_rnd1) as s09_dist_m_rnd1,
min("public".t_can_full1.s10_dist_m_rnd1) as s10_dist_m_rnd1,
min("public".t_can_full1.s11_dist_m_rnd1) as s11_dist_m_rnd1,
min("public".t_can_full1.s12_dist_m_rnd1) as s12_dist_m_rnd1,
min("public".t_can_full1.s13_dist_m_rnd1) as s13_dist_m_rnd1,
min("public".t_can_full1.s14_dist_m_rnd1) as s14_dist_m_rnd1,
min("public".t_can_full1.s15_dist_m_rnd1) as s15_dist_m_rnd1,
min("public".t_can_full1.s16_dist_m_rnd1) as s16_dist_m_rnd1,
min("public".t_can_full1.s17_dist_m_rnd1) as s17_dist_m_rnd1,
min("public".t_can_full1.s18_dist_m_rnd1) as s18_dist_m_rnd1,
--
-- min("public".t_can_full1.s01_ttc_s) as s01_ttc_s,
-- min("public".t_can_full1.s02_ttc_s) as s02_ttc_s,
-- min("public".t_can_full1.s03_ttc_s) as s03_ttc_s,
-- min("public".t_can_full1.s04_ttc_s) as s04_ttc_s,
-- min("public".t_can_full1.s05_ttc_s) as s05_ttc_s,
-- min("public".t_can_full1.s06_ttc_s) as s06_ttc_s,
-- min("public".t_can_full1.s07_ttc_s) as s07_ttc_s,
-- min("public".t_can_full1.s08_ttc_s) as s08_ttc_s,
-- min("public".t_can_full1.s09_ttc_s) as s09_ttc_s,
-- min("public".t_can_full1.s10_ttc_s) as s10_ttc_s,
-- min("public".t_can_full1.s11_ttc_s) as s11_ttc_s,
-- min("public".t_can_full1.s12_ttc_s) as s12_ttc_s,
-- min("public".t_can_full1.s13_ttc_s) as s13_ttc_s,
-- min("public".t_can_full1.s14_ttc_s) as s14_ttc_s,
-- min("public".t_can_full1.s15_ttc_s) as s15_ttc_s,
-- min("public".t_can_full1.s16_ttc_s) as s16_ttc_s,
-- min("public".t_can_full1.s17_ttc_s) as s17_ttc_s,
-- min("public".t_can_full1.s18_ttc_s) as s18_ttc_s,
-- --
-- min("public".t_can_full1.s01_ttc_s_rnd) as s01_ttc_s_rnd,
-- min("public".t_can_full1.s02_ttc_s_rnd) as s02_ttc_s_rnd,
-- min("public".t_can_full1.s03_ttc_s_rnd) as s03_ttc_s_rnd,
-- min("public".t_can_full1.s04_ttc_s_rnd) as s04_ttc_s_rnd,
-- min("public".t_can_full1.s05_ttc_s_rnd) as s05_ttc_s_rnd,
-- min("public".t_can_full1.s06_ttc_s_rnd) as s06_ttc_s_rnd,
-- min("public".t_can_full1.s07_ttc_s_rnd) as s07_ttc_s_rnd,
-- min("public".t_can_full1.s08_ttc_s_rnd) as s08_ttc_s_rnd,
-- min("public".t_can_full1.s09_ttc_s_rnd) as s09_ttc_s_rnd,
-- min("public".t_can_full1.s10_ttc_s_rnd) as s10_ttc_s_rnd,
-- min("public".t_can_full1.s11_ttc_s_rnd) as s11_ttc_s_rnd,
-- min("public".t_can_full1.s12_ttc_s_rnd) as s12_ttc_s_rnd,
-- min("public".t_can_full1.s13_ttc_s_rnd) as s13_ttc_s_rnd,
-- min("public".t_can_full1.s14_ttc_s_rnd) as s14_ttc_s_rnd,
-- min("public".t_can_full1.s15_ttc_s_rnd) as s15_ttc_s_rnd,
-- min("public".t_can_full1.s16_ttc_s_rnd) as s16_ttc_s_rnd,
-- min("public".t_can_full1.s17_ttc_s_rnd) as s17_ttc_s_rnd,
-- min("public".t_can_full1.s18_ttc_s_rnd) as s18_ttc_s_rnd,
--
min("public".t_can_full1.speed_kmh) as speed_kmh,
min("public".t_can_full1.speed_kmh_diff) as speed_kmh_diff,
min("public".t_can_full1.acclat_ms2) as acclat_ms2,
min("public".t_can_full1.acclat_ms2_diff) as acclat_ms2_diff,
min("public".t_can_full1.acclong_ms2) as acclong_ms2,
min("public".t_can_full1.acclong_ms2_diff) as acclong_ms2_diff,
min("public".t_can_full1.yawrate_degs) as yawrate_degs,
min("public".t_can_full1.yawrate_degs_diff) as yawrate_degs_diff,
min("public".t_can_full1.brakepress_bar) as brakepress_bar,
min("public".t_can_full1.brakepress_bar_diff) as brakepress_bar_diff,
min("public".t_can_full1.brakepress_status) as brakepress_status,
min("public".t_can_full1.steerangle_deg) as steerangle_deg,
min("public".t_can_full1.steerangle_deg_diff) as steerangle_deg_diff,
min("public".t_can_full1.steerangle_speed) as steerangle_speed,
min("public".t_can_full1.steerangle_speed_diff) as steerangle_speed_diff,
min("public".t_can_full1.accpedalpos_perc) as accpedalpos_perc,
min("public".t_can_full1.accpedalpos_perc_diff) as accpedalpos_perc_diff,
min("public".t_can_full1.ind_left) as ind_left,
min("public".t_can_full1.ind_right) as ind_right,
min("public".t_can_full1.ind) as ind,
min("public".t_can_full1.ldw_side) as ldw_side,
min("public".t_can_full1.ldw_tlc_s) as ldw_tlc_s,
min("public".t_can_full1.ldw_tlc_s_diff) as ldw_tlc_s_diff,
min("public".t_can_full1.ldw_dlc_m) as ldw_dlc_m,
min("public".t_can_full1.ldw_dlc_m_diff) as ldw_dlc_m_diff,
min("public".t_can_full1.dist_intersect_m) as dist_intersect_m,
min("public".t_can_full1.road_type) as road_type,
min("public".t_can_full1.lanes_count) as lanes_count,
--
min("public".t_can_full1.filename) as filename,
min("public".t_can_full1.cond) as cond,
min("public".t_can_full1.exid) as exid,
min("public".t_can_full1."date") as "date"

FROM
"public".t_can_full1

WHERE
"public".t_can_full1.subid = 3

GROUP BY
"public".t_can_full1.subid,
"public".t_can_full1.round_txt,
"public".t_can_full1.dist_m_rnd0

ORDER BY
min("public".t_can_full1.rownr)